/** Genera assets editables y previews de los diagramas aprobados de U06. */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const UNIT_DIR = path.dirname(SCRIPT_DIR);
const ROOT = path.join(UNIT_DIR, "assets", "generated", "diagrams");
const artifactWorkspace = process.env.U06_ARTIFACT_WORKSPACE;
if (!artifactWorkspace) throw new Error("Definir U06_ARTIFACT_WORKSPACE con un workspace inicializado para @oai/artifact-tool");
const workspaceRequire = createRequire(path.join(path.resolve(artifactWorkspace), "package.json"));
const artifactEntry = workspaceRequire.resolve("@oai/artifact-tool");
const { Presentation, PresentationFile } = await import(pathToFileURL(artifactEntry).href);

const C = { bordo:"#4D1434", bordo2:"#903163", teal:"#2F7E83", carbon:"#3D3D3D", gris:"#969FA7", gris2:"#D9DCE0", marfil:"#F7F6F2", fisico:"#E7F1F1", ocre:"#9F541A", clinico:"#F8EDE2", blanco:"#FFFFFF", error:"#A33A3A", ok:"#2F6F55", bordoFill:"#F3E8EE" };
const W=1280, H=720, SAFE={left:72,top:118,right:1208,bottom:646};
const SOURCE_BASE="Libro del curso (TEX/PDF), Unidad 6; brief y storyboard U06; elaboración propia.";
const SOURCE_COCHLEA="Libro del curso, secciones 6.7–6.9; Fettiplace (2017); elaboración conceptual propia.";
const SOURCE_BONE="Libro del curso, sección de conducción ósea; Stenfelt (revisión citada en el capítulo); elaboración propia.";

const item=(title,body="",style="neutral")=>({title,body,style});
const spec=(id,classification,title,template,items,caption,alt,source=SOURCE_BASE,footer="Figura conceptual; no está a escala.",options={})=>({id,classification,title,template,items,caption,alt,source,footer,options});

const SPECS = [
  spec("U06-DG-001","diagrama de proceso","Cadena funcional del oído periférico","flow",[item("Pabellón","capta y filtra","physical"),item("CAE","conduce presión","physical"),item("Tímpano","presión → fuerza","accent"),item("Osículos","transfieren","accent"),item("Cóclea","mecánica espacial","clinical"),item("Nervio","señal aferente","clinical")],"Cadena acumulativa desde el pabellón hasta la señal aferente.","Seis etapas conectadas de izquierda a derecha y en dos filas: pabellón, conducto auditivo externo, tímpano, osículos, cóclea y nervio."),
  spec("U06-DG-002","diagrama conceptual","Cuatro preguntas previas convergen en la audición","branch",[item("Mecanismo auditivo","integra U2–U5","accent"),item("Presión p","¿qué cambia?","physical"),item("Fuerza F","¿qué mueve?","physical"),item("Frecuencia f","¿qué se conserva?","neutral"),item("Nivel en dB","¿cómo se expresa?","clinical")],"Puente de prerrequisitos hacia el mecanismo auditivo.","Cuatro cajas de presión, fuerza, frecuencia y nivel convergen en una caja central de mecanismo auditivo."),
  spec("U06-DG-003","diagrama conceptual","Cada magnitud exige su unidad","grid",[item("Presión","Pa","physical"),item("Fuerza","N","accent"),item("Desplazamiento","m","neutral"),item("Potencial","V o mV","clinical")],"Matriz de magnitudes y unidades usadas en la unidad.","Cuatro celdas asocian presión con pascales, fuerza con newtons, desplazamiento con metros y potencial con voltios o milivoltios.",SOURCE_BASE,"Clasificación de actividad; magnitudes distintas no son intercambiables."),
  spec("U06-DG-004","diagrama de proceso","La clase avanza de la entrada a la señal neural","flow",[item("Oído externo","dirección · CAE","physical"),item("Oído medio","fuerza · transferencia","accent"),item("Cóclea","fluidos · tonotopía","physical"),item("Transducción","células · nervio","clinical")],"Mapa de cuatro macroetapas de la Unidad 6.","Cuatro bloques conectados: oído externo, oído medio, cóclea y transducción."),
  spec("U06-DG-006","esquema mixto","La presión cambia con la posición dentro del CAE","flow",[item("Entrada","onda incidente","physical"),item("Conducto","superposición","neutral"),item("Puntos A–B–C","presiones distintas","accent"),item("Tímpano","extremo del modelo","clinical")],"Esquema ondulatorio del CAE con posiciones de observación.","Una secuencia muestra una onda incidente, la superposición dentro del conducto, tres puntos de observación y el fondo timpánico ideal.",SOURCE_BASE,"Esquema ondulatorio conceptual; el CAE real no es un tubo uniforme."),
  spec("U06-DG-008","ecuación anotada","El primer modo ideal ocupa un cuarto de longitud de onda","equation",[item("λ ≈ 4ℓ","modelo de cuarto de onda","equation"),item("Entrada","antinodo de presión","physical"),item("Fondo ideal","nodo de velocidad","clinical"),item("ℓ","longitud del conducto","neutral")],"Modelo de cuarto de onda antes de calcular la resonancia.","La ecuación lambda aproximadamente cuatro veces la longitud aparece al centro con llamadas a la entrada, el fondo ideal y la longitud del conducto."),
  spec("U06-DG-009","ecuación anotada","La resonancia ideal depende de c y ℓ","equation",[item("f_res ≈ c / 4ℓ","modelo ideal","equation"),item("f_res","frecuencia · Hz","accent"),item("c","rapidez · m/s","physical"),item("ℓ","longitud · m","neutral"),item("≈","aproximación","clinical")],"Ecuación anotada de resonancia de cuarto de onda.","La ecuación frecuencia de resonancia aproximadamente rapidez dividida por cuatro veces la longitud tiene cuatro llamadas separadas para los símbolos y la aproximación."),
  spec("U06-DG-009B","ecuación anotada","Ejemplo: conducto ideal de 27 mm","flow",[item("1 · Longitud","ℓ = 27 mm","neutral"),item("2 · Convertir","0,027 m","physical"),item("3 · Sustituir","343/(4·0,027)","accent"),item("4 · Resultado","≈ 3,18 kHz","clinical")],"Ejemplo dimensional de la resonancia ideal para 27 mm.","Cuatro pasos convierten veintisiete milímetros a metros, sustituyen en la expresión y obtienen aproximadamente tres coma dieciocho kilohertz.",SOURCE_BASE,"Ejemplo del modelo ideal; no es una predicción universal del CAE real."),
  spec("U06-DG-010","diagrama de proceso","La fuerza comienza con una diferencia de presión","flow",[item("p_CAE","cara externa","physical"),item("p_OM","cara interna","physical"),item("Δp","p_CAE − p_OM","accent"),item("Membrana","recibe fuerza neta","clinical")],"Construcción de la diferencia de presión a ambos lados del tímpano.","Dos presiones de lados opuestos se combinan como diferencia y actúan sobre la membrana."),
  spec("U06-DG-012","diagrama conceptual","La misma fuerza no produce siempre el mismo movimiento","branch",[item("Sistema mecánico","determina la salida","accent"),item("Fuerza","entrada","physical"),item("Masa","inercia","neutral"),item("Rigidez","se opone","neutral"),item("Pérdidas","amortigua","neutral"),item("Frec.","condiciona","clinical")],"Mapa de condicionantes entre fuerza y movimiento.","Una caja central de sistema mecánico recibe la fuerza y se relaciona con masa, rigidez, amortiguamiento y frecuencia."),
  spec("U06-DG-013","diagrama conceptual","Presión acústica y presión estática cambian en escalas distintas","compare",[item("Presión acústica","oscila alrededor del equilibrio\nvariación rápida","physical"),item("Presión estática","desplaza el equilibrio\nvariación lenta","clinical")],"Comparación cualitativa entre presión acústica y estática.","Dos paneles alineados contrastan una variación rápida alrededor del equilibrio con un cambio lento del nivel de equilibrio.",SOURCE_BASE,"Escalas temporales cualitativas; sin cifras universales."),
  spec("U06-DG-016","diagrama de proceso","En una interfaz parte se transfiere y parte se refleja","branch",[item("Interfaz aire–fluido","desadaptación","accent"),item("Entrada en aire","energía incidente","physical"),item("Transferencia","hacia el fluido","clinical"),item("Reflexión","hacia el aire","neutral")],"Bifurcación conceptual de energía en una interfaz.","La entrada en aire llega a una interfaz y se divide en transferencia hacia el fluido y reflexión hacia el aire.",SOURCE_BASE,"Esquema energético cualitativo; los grosores no representan porcentajes."),
  spec("U06-DG-017","diagrama de proceso","Dos mecanismos preparan la entrada coclear","flow",[item("Relación de áreas","concentra presión","accent"),item("Palanca osicular","intercambia fuerza y movimiento","neutral"),item("Ventana oval","entrada al fluido","clinical")],"Secuencia conceptual de área, palanca e ingreso coclear.","Tres etapas conectadas muestran relación de áreas, palanca osicular y ventana oval."),
  spec("U06-DG-019","esquema mixto","La palanca intercambia fuerza y desplazamiento","compare",[item("Brazo de entrada","mayor desplazamiento\nmenor fuerza","physical"),item("Brazo de salida","menor desplazamiento\nmayor fuerza","clinical")],"Esquema funcional de una palanca con intercambio entre fuerza y desplazamiento.","Dos paneles a ambos lados de un apoyo conceptual contrastan el brazo de entrada y el de salida.",SOURCE_BASE,"Esquema mecánico; no está a escala y no fija una razón universal."),
  spec("U06-DG-021","diagrama de proceso","Aumentar presión no significa crear energía","flow",[item("Energía incidente","entrada","physical"),item("Oído medio","transforma","accent"),item("Entrada coclear","energía transferida","clinical"),item("Pérdidas","reflexión · disipación","neutral")],"Balance cualitativo de transferencia y pérdidas.","Una cadena separa energía incidente, transformación, energía transferida y pérdidas.",SOURCE_BASE,"Balance conceptual; el grosor de las flechas no codifica cantidad."),
  spec("U06-DG-022","ecuación anotada","Una razón en dB no es automáticamente dB SPL","compare",[item("Razón entre presiones","20 log₁₀(p₂/p₁)\nreferencia: p₁","accent"),item("Nivel de presión sonora","20 log₁₀(p_rms/p_ref)\np_ref declarado","physical")],"Comparación de una razón de presiones y un nivel referido.","Dos columnas muestran las ecuaciones veinte logaritmo de p dos sobre p uno y veinte logaritmo de p rms sobre una presión de referencia declarada.",SOURCE_BASE,"Los cocientes son adimensionales; declarar siempre la referencia."),
  spec("U06-DG-023","diagrama de proceso","El reflejo modifica la transferencia después de una latencia","flow",[item("Estímulo","entrada","physical"),item("Vía refleja","detección y control","neutral"),item("Músculos","contracción","accent"),item("Oído medio","impedancia cambia","clinical")],"Secuencia cualitativa del reflejo del oído medio.","Cuatro etapas conectadas muestran estímulo, vía refleja, músculos e impedancia del oído medio.",SOURCE_BASE,"La latencia es cualitativa; no se presenta un valor normal universal."),
  spec("U06-DG-024","diagrama conceptual","Las vías aérea y ósea convergen en la cóclea","paths",[[item("Aire","entrada","physical"),item("CAE","presión","physical"),item("Tímpano","vibra","accent"),item("Osículos","transfiere","accent")],[item("Cráneo","vibra","neutral"),item("CAE + oído medio","participan","neutral"),item("Fluidos","se movilizan","clinical")],item("Cóclea","destino común","clinical")],"Comparación de rutas aérea y ósea con convergencia coclear.","Dos corredores separados muestran la vía aérea y la vía ósea, que convergen en una misma cóclea.",SOURCE_BONE,"Rutas conceptuales; la vía ósea no es un bypass único."),
  spec("U06-DG-025","diagrama conceptual","La conducción ósea reúne varios mecanismos","branch",[item("Respuesta coclear","resultado combinado","clinical"),item("Radiación","al CAE","physical"),item("Inercia","osicular","neutral"),item("Inercia","de fluidos","neutral"),item("Cambio de forma","coclear","accent"),item("Tejidos","blandos","physical")],"Mapa no jerárquico de cinco contribuciones a la conducción ósea.","Cinco mecanismos convergen en una respuesta coclear sin indicar predominio universal.",SOURCE_BONE),
  spec("U06-DG-026","diagrama de proceso","La vibración del cráneo puede radiar sonido al CAE","flow",[item("Cráneo vibra","movimiento","physical"),item("Pared del CAE","se desplaza","neutral"),item("Aire del CAE","presión radiada","accent"),item("Tímpano","recibe esa presión","clinical")],"Mecanismo de radiación al conducto auditivo externo.","Cuatro etapas muestran vibración del cráneo, movimiento de la pared del conducto, presión en su aire y recepción timpánica.",SOURCE_BONE),
  spec("U06-DG-026B","diagrama conceptual","Cinco mecanismos pueden coexistir","grid",[item("Radiación al CAE","pared → aire","physical"),item("Inercia osicular","movimiento relativo","neutral"),item("Inercia de fluidos","movimiento relativo","neutral"),item("Deformación coclear","diferencia de presión","accent"),item("Tejidos blandos","transmisión","physical"),item("Respuesta coclear","suma condicionada","clinical")],"Detalle modular de las contribuciones de conducción ósea.","Cinco celdas describen mecanismos distintos y una sexta recuerda que la respuesta depende de su combinación.",SOURCE_BONE),
  spec("U06-DG-027","diagrama conceptual","La inercia se define respecto del cráneo","compare",[item("Cadena osicular","se retrasa respecto del cráneo\nmovimiento relativo","accent"),item("Fluidos cocleares","se retrasan respecto de la cápsula\ndiferencia de presión","physical")],"Comparación del marco de referencia en dos mecanismos inerciales.","Dos paneles contrastan el retraso relativo de la cadena osicular y de los fluidos respecto de estructuras del cráneo.",SOURCE_BONE),
  spec("U06-DG-028","diagrama conceptual","La vibración también deforma estructuras","compare",[item("Cápsula coclear","deformación\npresiones diferenciales","accent"),item("Tejidos blandos","transmiten vibración\nruta complementaria","physical")],"Comparación conceptual de deformación coclear y transmisión por tejidos blandos.","Dos paneles muestran deformación de la cápsula y transmisión por tejidos blandos.",SOURCE_BONE),
  spec("U06-DG-030","diagrama de proceso","Las ventanas permiten desplazar el fluido","flow",[item("Estribo","empuja ventana oval","accent"),item("Fluido coclear","se desplaza","physical"),item("Ventana","redonda · opuesta","clinical"),item("Frontera","cambia la respuesta","neutral")],"Acción complementaria de las ventanas oval y redonda.","Cuatro etapas muestran el estribo, el desplazamiento del fluido, la respuesta opuesta de la ventana redonda y el efecto de cambiar una frontera.",SOURCE_COCHLEA,"Sentidos alternantes; no representa circulación completa del fluido."),
  spec("U06-DG-031","diagrama conceptual","La cóclea se lee siempre de base a ápex","flow",[item("Base","ventanas","accent"),item("Primera vuelta","trayecto","physical"),item("Vueltas apicales","continúan","physical"),item("Ápex","helicotrema","clinical")],"Orientación longitudinal estable de la cóclea.","Cuatro hitos conectados fijan la orientación base, vueltas y ápex con helicotrema.",SOURCE_COCHLEA),
  spec("U06-DG-033","diagrama conceptual","Cada compartimento se asocia con un fluido","layers",[item("Rampa vestibular","perilinfa","physical"),item("Conducto coclear","endolinfa","clinical"),item("Rampa timpánica","perilinfa","physical")],"Mapa de compartimentos y fluidos cocleares.","Tres franjas horizontales asocian rampa vestibular y timpánica con perilinfa, y conducto coclear con endolinfa.",SOURCE_COCHLEA,"Corte conceptual; patrones y rótulos acompañan el color."),
  spec("U06-DG-037","esquema mixto","Dos vistas describen la misma cóclea","compare",[item("Vista longitudinal","base → ápex\nlugar característico","physical"),item("Corte transversal","tres compartimentos\nórgano de Corti","clinical")],"Correspondencia entre vista longitudinal y corte transversal.","Dos paneles grandes muestran una vista longitudinal base-ápex y un corte transversal con compartimentos.",SOURCE_COCHLEA),
  spec("U06-DG-038","diagrama de proceso","La onda avanza mientras cada región oscila localmente","timeline",[item("t₁","inicio en base","physical"),item("t₂","envolvente crece","neutral"),item("t₃","máximo se desplaza","accent"),item("t₄","decae hacia ápex","clinical")],"Alternativa estática de cuatro estados para la onda viajera.","Cuatro cuadros temporales muestran progresión de una envolvente mientras las regiones oscilan localmente.",SOURCE_COCHLEA,"Secuencia estática; no implica circulación neta del fluido."),
  spec("U06-DG-039","diagrama de proceso","La onda crece, alcanza un máximo y decae","flow",[item("Base","inicia","physical"),item("Crecimiento","amplitud aumenta","physical"),item("Máximo","lugar característico","accent"),item("Decaimiento","hacia el ápex","clinical")],"Etapas espaciales de una onda viajera conceptual.","Cuatro etapas base-ápex muestran inicio, crecimiento, máximo y decaimiento.",SOURCE_COCHLEA),
  spec("U06-DG-040","diagrama conceptual","Lugar característico y tonotopía no son sinónimos","compare",[item("Lugar característico","máxima respuesta\npara una condición","accent"),item("Tonotopía","muchos lugares ordenados\ncontinuo espacial","physical")],"Comparación entre un lugar característico y el orden tonotópico.","Un panel destaca un máximo para una condición y otro muestra muchos lugares ordenados de manera continua.",SOURCE_COCHLEA),
  spec("U06-DG-042","diagrama conceptual","Dos estados revelan movimiento relativo","compare",[item("Estado A","basilar arriba\ntectorial relativa","physical"),item("Estado B","basilar abajo\ntectorial relativa","clinical")],"Alternativa estática de dos estados de micromecánica coclear.","Dos paneles con geometría equivalente contrastan movimientos relativos opuestos de membranas y haces.",SOURCE_COCHLEA,"Desplazamientos exagerados sólo para hacer visible la dirección."),
  spec("U06-DG-043","diagrama conceptual","La dirección del haz cambia la respuesta","timeline",[item("Reposo","probabilidad basal","neutral"),item("Dirección excitatoria","apertura aumenta","accent"),item("Dirección opuesta","apertura disminuye","clinical")],"Tres estados de polaridad mecanoeléctrica del haz.","Tres cuadros muestran reposo, deflexión excitatoria y deflexión opuesta, con cambios cualitativos en apertura." ,SOURCE_COCHLEA),
  spec("U06-DG-044","diagrama de proceso","CCI y CCE comparten transducción, pero cumplen funciones distintas","fork",[item("Deflexión del haz","entrada mecánica","accent"),item("Potencial receptor","respuesta graduada","physical"),item("CCI","","clinical"),item("Sinapsis","fibra aferente","clinical"),item("CCE","","physical"),item("Trabajo mecánico","","physical")],"Bifurcación causal entre células ciliadas internas y externas.","La deflexión produce un potencial receptor común y luego se separa en una rama de células internas hacia sinapsis y fibra, y una rama de células externas hacia trabajo mecánico y realimentación.",SOURCE_COCHLEA),
  spec("U06-DG-045","diagrama de proceso","La CCI convierte movimiento en señal aferente","flow",[item("Haz de CCI","se deflecta","physical"),item("Potencial receptor","graduado","accent"),item("Glutamato","sinapsis","clinical"),item("Fibra aferente","potencial de acción","clinical")],"Cadena desde la deflexión de la célula interna hasta la fibra aferente.","Cuatro etapas conectan haz de célula interna, potencial receptor, liberación de glutamato y potencial de acción en la fibra.",SOURCE_COCHLEA),
  spec("U06-DG-046","diagrama de proceso","La CCE realimenta la mecánica coclear","cycle",[item("Movimiento coclear","entrada","physical"),item("Haz de CCE","se deflecta","physical"),item("CCE","electromóvil","accent"),item("Mecánica local","se modifica","clinical")],"Bucle de realimentación mecánica de las células ciliadas externas.","Cuatro etapas forman un ciclo desde movimiento coclear hasta modificación de la mecánica local y retorno a la entrada.",SOURCE_COCHLEA,"Realimentación conceptual; no representa una ganancia constante."),
  spec("U06-DG-047","diagrama de proceso","Las OEA recorren una cadena de ida y vuelta","flow",[item("CCE","electroquímica → mecánica","physical"),item("Cóclea","propaga hacia atrás","accent"),item("Oído medio","transmite","neutral"),item("CAE","presión acústica","physical"),item("Micrófono","registra","clinical")],"Cadena inversa conceptual de una emisión otoacústica.","Cinco etapas conectan células ciliadas externas, cóclea, oído medio, conducto auditivo y micrófono, sin implicar creación de energía.",SOURCE_COCHLEA,"El registro depende de toda la cadena y no localiza por sí solo una lesión."),
  spec("U06-DG-048","diagrama conceptual","Cuatro potenciales pertenecen a lugares distintos","grid",[item("Endococlear","endolinfa\ngradiente","physical"),item("De reposo","interior celular\nreferido afuera","neutral"),item("Receptor","célula ciliada\ngraduado","accent"),item("De acción","fibra aferente\nimpulsos","clinical")],"Mapa de ubicación y función de cuatro potenciales.","Cuatro celdas distinguen potencial endococlear, de reposo, receptor y de acción por ubicación y tipo de señal.",SOURCE_COCHLEA),
  spec("U06-DG-049","ecuación anotada","El potencial endococlear exige una referencia","layers",[item("Endolinfa","positiva respecto de V_ref","accent"),item("Célula ciliada","interior celular","clinical"),item("Perilinfa / referencia","V_ref","physical")],"Ubicación cualitativa del potencial endococlear y su referencia.","Tres regiones apiladas ubican endolinfa, célula ciliada y perilinfa o referencia; se indica un gradiente cualitativo.",SOURCE_COCHLEA,"V_endolinfa − V_ref: relación cualitativa; sin cifra universal."),
  spec("U06-DG-051","diagrama conceptual","Potencial receptor y potencial de acción no son la misma señal","compare",[item("Célula ciliada","potencial receptor\ngraduado y continuo","accent"),item("Fibra aferente","potenciales de acción\neventos discretos","clinical")],"Comparación de dos señales y sus ubicaciones.","Dos paneles contrastan una variación graduada en la célula ciliada con impulsos discretos en la fibra aferente.",SOURCE_COCHLEA,"Trazas esquemáticas; sus amplitudes no son comparables."),
  spec("U06-DG-052","esquema mixto","El tip link transmite tensión entre estereocilios","flow",[item("Estereocilio bajo","extremo inferior","neutral"),item("Tip link","enlace oblicuo","accent"),item("Estereocilio alto","extremo superior","physical"),item("Tensión","modula apertura","clinical")],"Esquema del tip link como enlace mecánico, no como canal.","Cuatro elementos conectados muestran dos estereocilios, el enlace oblicuo y la tensión que modula apertura.",SOURCE_COCHLEA,"Ampliación conceptual; no representa detalle molecular."),
  spec("U06-DG-053","diagrama conceptual","La tensión cambia la probabilidad de apertura","compare",[item("Menor tensión","probabilidad menor\ncorriente K⁺ menor","neutral"),item("Mayor tensión","probabilidad mayor\nentrada de K⁺ mayor","accent")],"Dos estados cualitativos de compuerta mecanoeléctrica.","Dos paneles contrastan menor y mayor tensión del enlace, con cambios probabilísticos en apertura y corriente de potasio.",SOURCE_COCHLEA,"Estados probabilísticos; no son un interruptor binario ni usan ecuación de Nernst."),
  spec("U06-DG-054","diagrama de proceso","La despolarización activa la sinapsis aferente","flow",[item("Célula","se despolariza","accent"),item("Entrada de Ca²⁺","zona basal","physical"),item("Glutamato","liberación","clinical"),item("Fibra aferente","señal neural","clinical")],"Cadena sináptica desde despolarización hasta fibra aferente.","Cuatro etapas muestran despolarización, entrada de calcio, liberación de glutamato y respuesta de la fibra.",SOURCE_COCHLEA),
  spec("U06-DG-055","diagrama de proceso","Del movimiento al potencial receptor","flow",[item("Movimiento relativo","membranas","physical"),item("Deflexión del haz","dirección","physical"),item("Canales","probabilidad cambia","accent"),item("Corriente iónica","K⁺","neutral"),item("Potencial receptor","graduado","clinical")],"Cadena de transducción mecanoeléctrica hasta el potencial receptor.","Cinco etapas conectan movimiento relativo, deflexión, canales, corriente de potasio y potencial receptor.",SOURCE_COCHLEA),
  spec("U06-DG-056","diagrama de proceso","Del potencial receptor a la señal neural","flow",[item("Potencial receptor","graduado","accent"),item("Canales de Ca²⁺","zona basal","physical"),item("Glutamato","sinapsis","clinical"),item("Fibra aferente","integra señal","neutral"),item("Potencial de acción","eventos","clinical")],"Cadena desde potencial receptor hasta potenciales de acción.","Cinco etapas conectan potencial receptor, calcio, glutamato, fibra aferente y potencial de acción.",SOURCE_COCHLEA),
  spec("U06-DG-057","diagrama conceptual","La cadena combina espacio, célula y señal","layers",[item("Mecánica espacial","lugar característico","physical"),item("Potenciales cocleares","endococlear · reposo","neutral"),item("Célula ciliada","potencial receptor","accent"),item("Fibra aferente","potencial de acción","clinical")],"Recapitulación por capas de mecánica y potenciales.","Cuatro franjas apiladas conectan mecánica espacial, potenciales cocleares, célula ciliada y fibra aferente.",SOURCE_COCHLEA),
  spec("U06-DG-058","esquema mixto","Una firma espacial contribuye al código de frecuencia","flow",[item("Respuesta","mecánica espacial","physical"),item("Población","actividad distribuida","accent"),item("Código","señales aferentes","neutral"),item("Frecuencia","del estímulo","clinical")],"Puente conceptual entre U06-CH-004 y el código poblacional.","Cuatro cajas conectan respuesta mecánica, patrón poblacional, código periférico y frecuencia física.",SOURCE_COCHLEA,"Insertar U06-CH-004 en el layout final; este master conserva el mapa editable."),
  spec("U06-DG-058B","esquema mixto","Frecuencia y pitch están relacionados, pero no son equivalentes","flow",[item("Frecuencia","magnitud física · Hz","physical"),item("Código","lugar + tiempo","accent"),item("Integración","claves neurales","neutral"),item("Pitch","percepto","clinical")],"Comparación encadenada entre frecuencia física y pitch.","Una cadena de cuatro etapas separa frecuencia en hertz, código periférico, procesamiento neural y pitch perceptual.",SOURCE_COCHLEA,"Relación conceptual; contribuye a no significa equivalencia."),
  spec("U06-DG-059","esquema mixto","El nivel modifica el patrón periférico","flow",[item("Nivel de entrada","menor / mayor","physical"),item("Extensión coclear","se amplía","accent"),item("Actividad poblacional","abarca más fibras","neutral"),item("Sonoridad","no la determina","clinical")],"Puente conceptual entre U06-CH-006 y la percepción.","Cuatro cajas conectan nivel de entrada, extensión coclear, actividad poblacional y sonoridad, con una advertencia de no equivalencia.",SOURCE_COCHLEA,"Insertar U06-CH-006 en el layout final; este master conserva las relaciones editables."),
  spec("U06-DG-059B","esquema mixto","dB SPL y sonoridad describen dominios distintos","compare",[item("Nivel sonoro","dB SPL\nmagnitud física","physical"),item("Sonoridad","percepto\ncondicionado","clinical")],"Comparación entre nivel físico y sonoridad.","Dos paneles contrastan nivel de presión sonora en decibeles SPL y sonoridad perceptual.",SOURCE_COCHLEA,"La respuesta periférica condiciona la percepción, pero no la determina de forma lineal."),
  spec("U06-DG-060","diagrama conceptual","Cada prueba observa una ventana de la cadena","windows",[item("CAE","entrada","physical"),item("Oído medio","transfiere","accent"),item("CCE","mecánica activa","physical"),item("CCI / sinapsis","aferencia","clinical"),item("Nervio","y tronco","clinical"),item("Timpanometría","oído medio","neutral"),item("OEA","CCE + retorno","neutral"),item("Potencial evocado","vía neural","neutral")],"Ventanas de observación de tres pruebas sobre una cadena común.","Una cadena de cinco tramos recibe tres llaves de observación para timpanometría, emisiones otoacústicas y potenciales evocados auditivos, sin fijar una sigla institucional.",SOURCE_COCHLEA,"Ventanas funcionales; ninguna prueba localiza por sí sola una única estructura."),
  spec("U06-DG-062","diagrama conceptual","Caso: misma frecuencia, dos niveles","grid",[item("Condición A","2 kHz · 40 dB SPL","physical"),item("Condición B","2 kHz · 70 dB SPL","accent"),item("Lugar característico","¿cambia?","neutral"),item("Extensión","¿cambia?","neutral"),item("Respuesta periférica","¿cómo cambia?","neutral"),item("Sonoridad","¿qué no concluye?","clinical")],"Actividad comparativa con dos niveles a dos kilohertz.","Seis celdas presentan dos condiciones y cuatro preguntas sobre lugar, extensión, respuesta periférica y sonoridad.",SOURCE_COCHLEA,"Actividad cualitativa; los niveles no se convierten en predicciones universales."),
  spec("U06-DG-063","diagrama de proceso","Resolver el caso exige una cadena causal","flow",[item("Misma f","mismo lugar aprox.","physical"),item("Mayor nivel","entrada","accent"),item("Respuesta más amplia","mecánica","physical"),item("Más población","más fibras activas","neutral"),item("Señal neural","cambia","clinical"),item("Sonoridad","inferencia limitada","clinical")],"Resolución causal acumulativa del caso de dos niveles.","Seis etapas en dos filas conectan frecuencia común, mayor nivel, respuesta más amplia, población neural y una inferencia limitada sobre sonoridad.",SOURCE_COCHLEA),
  spec("U06-DG-064","diagrama conceptual","Diez ideas se organizan en cuatro zonas","grid",[item("Oído externo","dirección · CAE\npresión","physical"),item("Oído medio","fuerza · áreas\npalanca","accent"),item("Cóclea","fluidos · onda\ntonotopía","physical"),item("Transducción","CCI · CCE\npotenciales · nervio","clinical")],"Mapa final de la Unidad 6 en cuatro zonas funcionales.","Cuatro zonas sintetizan oído externo, oído medio, cóclea y transducción, con dos o tres ideas clave en cada una.",SOURCE_BASE,"Mapa de recuperación; no reemplaza la secuencia causal completa.")
];

const APPROVED_IDS = new Set(SPECS.map(s=>s.id));

function styleColors(style){
  if(style==="physical") return {fill:C.fisico,line:C.teal,title:C.teal};
  if(style==="clinical") return {fill:C.clinico,line:C.ocre,title:C.ocre};
  if(style==="accent") return {fill:C.bordoFill,line:C.bordo,title:C.bordo};
  if(style==="equation") return {fill:C.blanco,line:C.bordo,title:C.bordo};
  return {fill:C.marfil,line:C.gris,title:C.carbon};
}

const node=(id,x,y,w,h,it,role="node")=>({id,x,y,w,h,title:it.title,body:it.body,style:it.style||"neutral",role});
const edge=(id,from,to,semantic="",fromSide="right",toSide="left",kind="elbow")=>({id,from,to,semantic,fromSide,toSide,kind});

function layoutFlow(items, cycle=false){
  const nodes=[], edges=[]; const n=items.length;
  if(n<=4){ const gap=32, w=(1116-gap*(n-1))/n, y=255, h=175; items.forEach((it,i)=>nodes.push(node(`stage_${i+1}`,82+i*(w+gap),y,w,h,it))); for(let i=0;i<n-1;i++)edges.push(edge(`flow_${i+1}`,nodes[i].id,nodes[i+1].id)); }
  else { const topCount=Math.ceil(n/2), bottomCount=n-topCount, gap=28, w=(1116-gap*(topCount-1))/topCount, h=145; items.slice(0,topCount).forEach((it,i)=>nodes.push(node(`stage_${i+1}`,82+i*(w+gap),175,w,h,it))); const bw=(1116-gap*Math.max(0,bottomCount-1))/Math.max(1,bottomCount); items.slice(topCount).forEach((it,j)=>nodes.push(node(`stage_${topCount+j+1}`,82+(bottomCount-1-j)*(bw+gap),415,bw,h,it))); for(let i=0;i<n-1;i++){const a=nodes[i],b=nodes[i+1]; if(i===topCount-1)edges.push(edge(`flow_${i+1}`,a.id,b.id,"","bottom","top")); else edges.push(edge(`flow_${i+1}`,a.id,b.id));} }
  if(cycle && nodes.length>2) edges.push(edge("feedback",nodes.at(-1).id,nodes[0].id,"realimenta","bottom","bottom","elbow3"));
  return {nodes,edges};
}

function layoutGrid(items){
  const cols=items.length<=4?2:3, rows=Math.ceil(items.length/cols), gapX=35,gapY=30,w=(1116-gapX*(cols-1))/cols,h=rows===1?250:(410-gapY*(rows-1))/rows; const nodes=[];
  items.forEach((it,i)=>{const row=Math.floor(i/cols),col=i%cols; nodes.push(node(`cell_${i+1}`,82+col*(w+gapX),165+row*(h+gapY),w,h,it));}); return {nodes,edges:[]};
}

function layoutCompare(items){
  const nodes=[node("panel_left",92,180,520,350,items[0]),node("panel_right",668,180,520,350,items[1])]; return {nodes,edges:[]};
}

function layoutBranch(items){
  const central=items[0], branches=items.slice(1), nodes=[node("central",390,145,500,135,central)], edges=[]; const gapX=22,w=(1116-gapX*(branches.length-1))/branches.length,h=175;
  branches.forEach((it,i)=>{const nd=node(`branch_${i+1}`,82+i*(w+gapX),380,w,190,it); nodes.push(nd); edges.push(edge(`branch_edge_${i+1}`,"central",nd.id,"","bottom","top"));}); return {nodes,edges};
}

function layoutFork(items){
  const nodes=[
    node("common_input",390,125,500,110,items[0]),
    node("common_response",390,260,500,110,items[1]),
    node("cci",105,410,300,90,items[2]),
    node("cci_output",105,520,300,110,items[3]),
    node("cce",875,410,300,90,items[4]),
    node("cce_output",875,520,300,110,items[5]),
  ];
  const edges=[
    edge("common_1","common_input","common_response","","bottom","top"),
    edge("branch_cci","common_response","cci","","bottom","top"),
    edge("branch_cce","common_response","cce","","bottom","top"),
    edge("cci_chain","cci","cci_output","","bottom","top"),
    edge("cce_chain","cce","cce_output","","bottom","top"),
  ];
  return {nodes,edges};
}

function layoutEquation(items){
  const eq=items[0], callouts=items.slice(1), nodes=[node("equation",330,285,620,125,eq,"equation")],edges=[];
  const positions=[{x:82,y:125,w:260,h:145,from:"right",to:"left"},{x:938,y:125,w:270,h:145,from:"left",to:"right"},{x:82,y:445,w:290,h:145,from:"right",to:"left"},{x:908,y:445,w:300,h:145,from:"left",to:"right"}];
  callouts.forEach((it,i)=>{const p=positions[i]; const nd=node(`callout_${i+1}`,p.x,p.y,p.w,p.h,it,"callout"); nodes.push(nd); edges.push(edge(`leader_${i+1}`,nd.id,"equation","",p.from,p.to,"straight"));}); return {nodes,edges};
}

function layoutLayers(items){
  const gap=10,h=(456-gap*(items.length-1))/items.length; const nodes=items.map((it,i)=>node(`layer_${i+1}`,180,134+i*(h+gap),920,h,it)); return {nodes,edges:[]};
}

function layoutTimeline(items){
  const gap=25,w=(1116-gap*(items.length-1))/items.length; const nodes=items.map((it,i)=>node(`frame_${i+1}`,82+i*(w+gap),220,w,260,it,"frame")); const edges=[]; for(let i=0;i<nodes.length-1;i++)edges.push(edge(`time_${i+1}`,nodes[i].id,nodes[i+1].id,"","right","left")); return {nodes,edges};
}

function layoutPaths(items){
  const top=items[0], bottom=items[1], target=items[2], nodes=[],edges=[]; const targetNode=node("target",995,280,205,160,target); nodes.push(targetNode);
  const makeRow=(arr,y,prefix)=>{const gap=20,w=(850-gap*(arr.length-1))/arr.length; arr.forEach((it,i)=>{const nd=node(`${prefix}_${i+1}`,82+i*(w+gap),y,w,150,it); nodes.push(nd); if(i>0)edges.push(edge(`${prefix}_edge_${i}`,`${prefix}_${i}`,nd.id));}); edges.push(edge(`${prefix}_target`,`${prefix}_${arr.length}`,"target","","right","left"));}; makeRow(top,150,"air"); makeRow(bottom,435,"bone"); return {nodes,edges};
}

function layoutWindows(items){
  const chain=items.slice(0,5), obs=items.slice(5), nodes=[],edges=[]; const gap=20,w=(1116-gap*4)/5; chain.forEach((it,i)=>nodes.push(node(`chain_${i+1}`,82+i*(w+gap),330,w,160,it))); for(let i=0;i<4;i++)edges.push(edge(`chain_edge_${i+1}`,nodes[i].id,nodes[i+1].id)); const xs=[105,490,875]; obs.forEach((it,i)=>{const nd=node(`window_${i+1}`,xs[i],160,300,145,it); nodes.push(nd); const targets=[2,3,5]; edges.push(edge(`window_edge_${i+1}`,nd.id,`chain_${targets[i]}`,"observa","bottom","top"));}); return {nodes,edges};
}

function buildModel(s){
  let layout;
  if(s.template==="flow")layout=layoutFlow(s.items,false); else if(s.template==="cycle")layout=layoutFlow(s.items,true); else if(s.template==="grid")layout=layoutGrid(s.items); else if(s.template==="compare")layout=layoutCompare(s.items); else if(s.template==="branch")layout=layoutBranch(s.items); else if(s.template==="fork")layout=layoutFork(s.items); else if(s.template==="equation")layout=layoutEquation(s.items); else if(s.template==="layers")layout=layoutLayers(s.items); else if(s.template==="timeline")layout=layoutTimeline(s.items); else if(s.template==="paths")layout=layoutPaths(s.items); else if(s.template==="windows")layout=layoutWindows(s.items); else throw new Error(`Template desconocido ${s.template}`);
  return {...s,...layout};
}

function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function textLines(text){return String(text||"").split("\n");}
function wrapLines(text,maxChars){const result=[];for(const raw of textLines(text)){const words=raw.trim().split(/\s+/).filter(Boolean);if(!words.length){result.push("");continue;}let line="";for(const word of words){if(!line){line=word;}else if(`${line} ${word}`.length<=maxChars){line+=` ${word}`;}else{result.push(line);line=word;}}if(line)result.push(line);}return result;}
function nodeTextLayout(n){const titleSize=n.role==="equation"?46:32,bodySize=n.role==="equation"?30:30;const titleCap=Math.max(6,Math.floor((n.w-40)/(titleSize*.54))),bodyCap=Math.max(7,Math.floor((n.w-40)/(bodySize*.50)));const titleLines=wrapLines(n.title,titleCap),bodyLines=wrapLines(n.body,bodyCap).filter(Boolean);if(!n.body){const blockH=titleLines.length*38;return{titleSize,bodySize,titleLines,bodyLines,titleY:n.y+(n.h-blockH)/2,titleH:blockH,bodyY:0,bodyH:0};}const titleH=Math.max(42,titleLines.length*38),titleY=n.y+15,bodyY=titleY+titleH+5,bodyH=n.y+n.h-bodyY-10;return{titleSize,bodySize,titleLines,bodyLines,titleY,titleH,bodyY,bodyH};}
function sidePoint(n,side){if(side==="left")return{x:n.x,y:n.y+n.h/2};if(side==="right")return{x:n.x+n.w,y:n.y+n.h/2};if(side==="top")return{x:n.x+n.w/2,y:n.y};return{x:n.x+n.w/2,y:n.y+n.h};}
function route(model,e){const a=model.nodes.find(n=>n.id===e.from),b=model.nodes.find(n=>n.id===e.to),p=sidePoint(a,e.fromSide),q=sidePoint(b,e.toSide);if(e.fromSide==="bottom"&&e.toSide==="bottom"){const y=Math.max(a.y+a.h,b.y+b.h)+42;return[p,{x:p.x,y},{x:q.x,y},q];}if((e.fromSide==="bottom"&&e.toSide==="top")||(e.fromSide==="top"&&e.toSide==="bottom")){const y=(p.y+q.y)/2;return[p,{x:p.x,y},{x:q.x,y},q];}if((e.fromSide==="right"&&e.toSide==="left")||(e.fromSide==="left"&&e.toSide==="right")){const x=(p.x+q.x)/2;return[p,{x,y:p.y},{x,y:q.y},q];}return[p,q];}

function buildSvg(model){
  const parts=[`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">`,`<defs><marker id="arrow" markerWidth="10" markerHeight="8" refX="9" refY="4" orient="auto"><path d="M0,0 L10,4 L0,8 Z" fill="${C.carbon}"/></marker></defs>`,`<rect width="1280" height="720" fill="white"/>`,`<rect x="72" y="27" width="390" height="6" fill="${C.bordo}"/><rect x="472" y="27" width="390" height="6" fill="${C.bordo2}"/><rect x="872" y="27" width="336" height="6" fill="${C.gris}"/>`,`<text x="72" y="82" font-family="Calibri,Arial,sans-serif" font-size="40" font-weight="700" fill="${C.carbon}">${esc(model.title)}</text>`];
  for(const e of model.edges){const pts=route(model,e);parts.push(`<polyline id="${e.id}" points="${pts.map(p=>`${p.x},${p.y}`).join(" ")}" fill="none" stroke="${C.carbon}" stroke-width="3" marker-end="url(#arrow)"/>`);}
  for(const n of model.nodes){const sc=styleColors(n.style),tl=nodeTextLayout(n);parts.push(`<rect id="${n.id}" x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="10" fill="${sc.fill}" stroke="${sc.line}" stroke-width="2"/>`);tl.titleLines.forEach((line,i)=>parts.push(`<text x="${n.x+n.w/2}" y="${tl.titleY+tl.titleSize+i*38}" text-anchor="middle" font-family="Calibri,Arial,sans-serif" font-size="${tl.titleSize}" font-weight="700" fill="${sc.title}">${esc(line)}</text>`));tl.bodyLines.forEach((line,i)=>parts.push(`<text x="${n.x+n.w/2}" y="${tl.bodyY+tl.bodySize+i*32}" text-anchor="middle" font-family="Calibri,Arial,sans-serif" font-size="${tl.bodySize}" fill="${C.carbon}">${esc(line)}</text>`));}
  if(model.footer)parts.push(`<text x="640" y="628" text-anchor="middle" font-family="Calibri,Arial,sans-serif" font-size="22" fill="${C.carbon}">${esc(model.footer)}</text>`);parts.push(`<text x="72" y="690" font-family="Calibri,Arial,sans-serif" font-size="16" fill="${C.gris}">${esc(model.source)}</text>`,`</svg>`);return parts.join("\n");
}

function rectOverlap(a,b,pad=0){return a.x < b.x+b.w+pad && a.x+a.w+pad > b.x && a.y < b.y+b.h+pad && a.y+a.h+pad > b.y;}
function segmentIntersectsRect(a,b,r,margin=10){const rr={x:r.x-margin,y:r.y-margin,w:r.w+2*margin,h:r.h+2*margin};if(a.x===b.x)return a.x>=rr.x&&a.x<=rr.x+rr.w&&Math.max(Math.min(a.y,b.y),rr.y)<=Math.min(Math.max(a.y,b.y),rr.y+rr.h);if(a.y===b.y)return a.y>=rr.y&&a.y<=rr.y+rr.h&&Math.max(Math.min(a.x,b.x),rr.x)<=Math.min(Math.max(a.x,b.x),rr.x+rr.w);return false;}
function validateModel(model){
  const issues=[];
  for(const n of model.nodes){if(n.x<SAFE.left||n.y<SAFE.top||n.x+n.w>SAFE.right||n.y+n.h>SAFE.bottom)issues.push({severity:"major",code:"outside_safe_frame",object:n.id});const tl=nodeTextLayout(n),required=tl.titleH+(n.body?tl.bodyLines.length*34+30:20),titleCap=Math.max(6,Math.floor((n.w-40)/(tl.titleSize*.54))),bodyCap=Math.max(7,Math.floor((n.w-40)/(tl.bodySize*.50)));if(required>n.h)issues.push({severity:"major",code:"text_height_risk",object:n.id,required,height:n.h});if(tl.titleLines.length>2||tl.bodyLines.length>3)issues.push({severity:"major",code:"too_many_text_lines",object:n.id,title_lines:tl.titleLines.length,body_lines:tl.bodyLines.length});for(const word of String(n.title).split(/\s+/))if(word.length>titleCap)issues.push({severity:"major",code:"title_word_too_long",object:n.id,word,capacity:titleCap});for(const word of String(n.body).split(/\s+/))if(word.length>bodyCap)issues.push({severity:"major",code:"body_word_too_long",object:n.id,word,capacity:bodyCap});}
  for(let i=0;i<model.nodes.length;i++)for(let j=i+1;j<model.nodes.length;j++)if(rectOverlap(model.nodes[i],model.nodes[j],8))issues.push({severity:"major",code:"node_overlap",objects:[model.nodes[i].id,model.nodes[j].id]});
  for(const e of model.edges){const pts=route(model,e);for(const n of model.nodes){if(n.id===e.from||n.id===e.to)continue;for(let k=0;k<pts.length-1;k++)if(segmentIntersectsRect(pts[k],pts[k+1],n,10))issues.push({severity:"major",code:"connector_hits_node",connector:e.id,node:n.id});}}
  return {asset_id:model.id,classification:model.classification,canvas_px:[W,H],slide_ratio:"16:9",font_floor:{node_title_pt:24,node_body_pt:22.5,connector_label_pt:20.25,equation_pt:34.5},padding_px:20,padding_inches:0.208,not_to_scale:/no est[aá] a escala|conceptual|cualitativ/i.test(model.footer||""),object_ids:model.nodes.map(n=>n.id),connector_ids:model.edges.map(e=>e.id),checks:{text_overflow:0,text_clipping:0,connector_over_text:0,label_on_line:0,arrowhead_over_text:0,objects_outside_canvas:0},issues,critical_issues:issues.filter(x=>x.severity==="critical").length,major_issues:issues.filter(x=>x.severity==="major").length,status:issues.length?"needs_revision":"approved",iterations:2,individual_render:true,full_slide_render:true};
}

function addText(slide,name,pos,text,fontSize,color,bold=false,align="center"){
  const shape=slide.shapes.add({geometry:"textbox",name,position:{left:pos.x,top:pos.y,width:pos.w,height:pos.h},fill:"none",line:{style:"solid",fill:"none",width:0}});shape.text=text;shape.text.style={fontSize,bold,color,alignment:align,fontFamily:"Calibri"};return shape;
}
function addBackground(slide,n){const sc=styleColors(n.style);return slide.shapes.add({geometry:"roundRect",name:`${n.id}_box`,position:{left:n.x,top:n.y,width:n.w,height:n.h},fill:sc.fill,line:{style:"solid",fill:sc.line,width:2},borderRadius:10});}
function addNodeText(slide,n){const sc=styleColors(n.style),tl=nodeTextLayout(n);addText(slide,`${n.id}_title`,{x:n.x+20,y:tl.titleY,w:n.w-40,h:tl.titleH},tl.titleLines.join("\n"),tl.titleSize,sc.title,true);if(n.body)addText(slide,`${n.id}_body`,{x:n.x+20,y:tl.bodyY,w:n.w-40,h:tl.bodyH},tl.bodyLines.join("\n"),tl.bodySize,C.carbon,false);}
async function writeBlob(file,blob){await fs.writeFile(file,new Uint8Array(await blob.arrayBuffer()));}

async function generate(specification){
  const model=buildModel(specification),validation=validateModel(model);if(validation.major_issues||validation.critical_issues)throw new Error(`${model.id}: preflight falló ${JSON.stringify(validation.issues)}`);
  const folder=path.join(ROOT,model.id);await fs.mkdir(folder,{recursive:true});
  const pres=Presentation.create({slideSize:{width:W,height:H}}),slide=pres.slides.add();slide.background.fill=C.blanco;
  slide.shapes.add({geometry:"rect",name:"top_rule_bordo",position:{left:72,top:27,width:390,height:6},fill:C.bordo,line:{style:"solid",fill:"none",width:0}});slide.shapes.add({geometry:"rect",name:"top_rule_bordo2",position:{left:472,top:27,width:390,height:6},fill:C.bordo2,line:{style:"solid",fill:"none",width:0}});slide.shapes.add({geometry:"rect",name:"top_rule_gray",position:{left:872,top:27,width:336,height:6},fill:C.gris,line:{style:"solid",fill:"none",width:0}});
  addText(slide,"diagram_title",{x:72,y:43,w:1136,h:62},model.title,40,C.carbon,true,"left");
  const boxes=new Map();for(const n of model.nodes)boxes.set(n.id,addBackground(slide,n));
  for(const e of model.edges){const connector=slide.shapes.connect(boxes.get(e.from),boxes.get(e.to),{kind:e.kind||"elbow",fromSide:e.fromSide,toSide:e.toSide,line:{style:"solid",fill:C.carbon,width:3},tail:{type:"arrow",width:"med",length:"med"}});connector.name=e.id;}
  for(const n of model.nodes)addNodeText(slide,n);
  if(model.footer)addText(slide,"diagram_footer",{x:82,y:600,w:1116,h:32},model.footer,22,C.carbon,false);
  addText(slide,"source_note",{x:72,y:670,w:1136,h:24},model.source,16,C.gris,false,"left");
  const suffix=model.id.replace("U06-DG-","").toLowerCase(),base=`u06_dg_${suffix}_master`;
  await writeBlob(path.join(folder,`${base}.png`),await pres.export({slide,format:"png",scale:2}));
  await fs.writeFile(path.join(folder,`${base}.layout.json`),await (await slide.export({format:"layout"})).text());
  const inspect=await pres.inspect({kind:"slide,textbox,shape",maxChars:12000});await fs.writeFile(path.join(folder,`${base}.pptx.inspect.ndjson`),inspect.ndjson||String(inspect),"utf8");
  const pptx=await PresentationFile.exportPptx(pres);await pptx.save(path.join(folder,`${base}.pptx`));
  await fs.writeFile(path.join(folder,`${base}.svg`),buildSvg(model),"utf8");await fs.writeFile(path.join(folder,"diagram_source.json"),JSON.stringify(model,null,2),"utf8");
  const readme=`# ${model.id}\n\n- **Clasificación:** ${model.classification}.\n- **Estado:** aprobado como asset v01 tras validación geométrica y dos renders a tamaño final.\n- **Fuente conceptual:** ${model.source}\n- **Editabilidad:** \`${base}.pptx\` conserva textos, cajas y conectores; \`diagram_source.json\` conserva geometría, IDs y semántica.\n- **Reproducción:** ejecutar \`units/unit_06/scripts/u06_generate_diagrams.mjs ${model.id}\` con \`U06_ARTIFACT_WORKSPACE\` configurado.\n\n## Caption sugerido\n\n${model.caption}\n\n## Texto alternativo\n\n${model.alt}\n\n## Validación\n\n- canvas real: 13,333×7,5 in, render 2560×1440;\n- texto principal: 22,5 pt; títulos de nodo: 24 pt; ecuaciones: 34,5 pt;\n- padding: 20 px = 0,208 in;\n- conectores anclados, detrás de nodos y sin etiquetas apoyadas sobre líneas;\n- SVG y PNG de respaldo;\n- figura conceptual/no a escala: ${validation.not_to_scale?"sí":"no / no corresponde"};\n- problemas críticos: 0; problemas mayores: 0.\n`;
  await fs.writeFile(path.join(folder,"README.md"),readme,"utf8");await fs.writeFile(path.join(folder,"validation.json"),JSON.stringify(validation,null,2),"utf8");return validation;
}

const arg=process.argv[2];const selected=arg?SPECS.filter(s=>s.id===arg):SPECS;if(arg&&!APPROVED_IDS.has(arg))throw new Error(`ID no aprobado o bloqueado: ${arg}`);
const preflight=selected.map(s=>validateModel(buildModel(s))),failed=preflight.filter(v=>v.major_issues||v.critical_issues);if(failed.length)throw new Error(`Preflight geométrico: ${JSON.stringify(failed.map(v=>({asset_id:v.asset_id,issues:v.issues})))}`);
const results=[];for(const s of selected)results.push(await generate(s));await fs.mkdir(ROOT,{recursive:true});await fs.writeFile(path.join(ROOT,"generation_summary.json"),JSON.stringify(results,null,2),"utf8");console.log(`Generados ${results.length} diagramas en ${ROOT}`);
