import fs from "node:fs/promises";
import path from "node:path";
import { Presentation, PresentationFile } from "@oai/artifact-tool";

const UNIT = path.resolve(import.meta.dirname, "..", "..");
const OUT = path.join(UNIT, "assets", "generated", "diagrams");
const W = 1280, H = 720;
const C = { bordo:"#4D1434", bordo2:"#903163", teal:"#2F7E83", tealL:"#E7F1F1", ocre:"#9F541A", ocreL:"#F8EDE2", carbon:"#242A2E", gray:"#969FA7", grid:"#D9DCE0", white:"#FFFFFF", ivory:"#FBF8F2" };

const metas = [
  ["U04-DG-001",16,"situacion_inicial","diagrama conceptual","Una fuente perturba el medio; el instrumento mide y el receptor responde.","Fuente, medio, punto de medición y receptor conectados por propagación, con cinco preguntas físicas alrededor.","Storyboard U04-002 y TEX 4.3."],
  ["U04-DG-002",17,"mapa_unidad","diagrama conceptual","La unidad avanza del fenómeno hacia una interpretación responsable.","Mapa de once etapas organizado en tres encuentros y leído de izquierda a derecha.","Storyboard U04-006/014/107."],
  ["U04-DG-003",18,"cadena_acustica","esquema mixto","Fenómeno físico, medición y percepción no son sinónimos.","Comparación físico-perceptual y cadena funcional fuente, medio, campo y receptor.","TEX 4.3 y storyboard U04-008–010."],
  ["U04-DG-004",19,"generacion","diagrama de proceso","La fuente oscila localmente y el aire sostiene la propagación.","Dos cadenas paralelas comparan generación vocal y electroacústica.","TEX 4.3 y NIDCD como referencia conceptual."],
  ["U04-DG-005",20,"propagacion_longitudinal","diagrama de proceso","Restauración e inercia transmiten la perturbación a regiones vecinas.","Cinco estados distinguen compresión, fuerza restauradora, movimiento local, nueva compresión y avance del frente.","TEX 4.4. Figura conceptual, no a escala."],
  ["U04-DG-006",21,"rapidez_medio","ecuación anotada","La rapidez depende de rigidez y densidad; al cambiar el medio, la frecuencia se conserva.","Ecuación c igual raíz de K sub s sobre rho con callouts y comparación entre dos medios.","TEX 4.4."],
  ["U04-DG-007",22,"campo_magnitudes","esquema mixto","Presión, velocidad de partícula y rapidez de propagación responden preguntas distintas.","Tres zonas muestran campo, presión relativa y contraste entre u y c.","TEX 4.5.1–4.5.2."],
  ["U04-DG-008",23,"impedancia_reflexion","esquema mixto","Un desajuste de impedancias produce reflexión y transmisión.","Dos medios separados por una interfaz reciben ondas incidente, reflejada y transmitida, con ecuaciones de Z y R p.","TEX 4.5.3–4.5.4. Figura conceptual, no a escala."],
  ["U04-DG-009",24,"intensidad_ecuaciones","ecuación anotada","La intensidad instantánea es un producto; la media depende de una ventana y de las hipótesis.","Ecuaciones de intensidad instantánea, media y onda plana con callouts de unidades y condiciones.","TEX 4.5.5."],
  ["U04-DG-010",25,"flujo_energia_medicion","diagrama de proceso","Área y tiempo conectan intensidad, potencia y energía.","Cadena I por superficie igual potencia y potencia por tiempo igual energía, con unidades bajo cada magnitud.","TEX 4.5.5 y 4.12."],
  ["U04-DG-011",26,"descriptores_callouts","esquema mixto","La elección del descriptor depende de la pregunta.","Matriz conceptual conecta instante, pico, pico a pico, media y RMS con su significado.","TEX 4.6; acompaña U04-CH-003."],
  ["U04-DG-012",27,"proceso_rms","esquema mixto","Cuadrar, promediar y extraer la raíz construyen el RMS.","Tres pasos con unidades Pa, Pa al cuadrado y Pa; la regla pico sobre raíz de dos se limita a senoides.","TEX 4.6.5."],
  ["U04-DG-013",28,"niveles_referencias","ecuación anotada","Todo nivel necesita magnitud, referencia y condiciones.","Tres niveles L p, L I y L W convergen en el criterio magnitud sobre referencia, seguido del contraste SPL, HL y sonoridad.","TEX 4.7."],
  ["U04-DG-014",29,"logica_suma","diagrama de proceso","Primero se decide la relación temporal; después se elige la suma.","Árbol con rutas coherente y no correlacionada, condiciones y resultados más seis o más tres decibeles.","TEX 4.8."],
  ["U04-DG-015",30,"geometrias_campos","diagrama conceptual","Geometría de frente y tipo de campo son decisiones diferentes.","Paneles de modelos plano, cilíndrico y esférico junto a campo libre, próximo y reverberante.","TEX 4.9. Figura conceptual, no a escala."],
  ["U04-DG-016",31,"ley_distancia","esquema mixto","El área esférica conecta distancia, intensidad y nivel.","Fuente con dos radios y cadena de cuatro pasos hasta la ley de diferencia de nivel.","TEX 4.10. Figura conceptual, no a escala."],
  ["U04-DG-017",32,"directividad","esquema mixto","La directividad redistribuye potencia y depende de frecuencia y dirección.","Comparación omnidireccional-direccional y ecuaciones de factor e índice de directividad.","TEX 4.11. Patrones conceptuales, no a escala."],
  ["U04-DG-018",33,"caso_integrador","esquema mixto","Una medición interpretable exige una cadena explícita de decisiones.","Proceso de seis nodos desde fuente y campo hasta sensor, procesamiento, nivel e informe.","TEX 4.8–4.12 y storyboard U04-104–107/124."],
  ["U04-DG-019",34,"errores","diagrama conceptual","Siete atajos frecuentes cambian el significado del resultado.","Siete pares alineados de error y corrección breve.","TEX 4.13 y brief de la Unidad 4."],
  ["U04-DG-020",35,"distancia_directividad","esquema mixto","Distancia y directividad pueden combinarse si comparten referencia y modelo.","Fuente direccional, dos puntos y cálculo por capas de distancia, directividad y suma final.","TEX 4.10–4.11."],
  ["U04-DG-021",36,"microvisuales","esquema mixto","Prerrequisitos, mecanismos y control RMS se muestran como ayudas breves.","Tres microvisuales independientes: prerrequisitos, mecanismos de generación y checklist RMS.","Storyboard U04-004/011/058."],
  ["U04-DG-022",37,"ejemplos_ecuaciones","ecuación anotada","Un ejemplo correcto explicita datos, relación, cálculo y verificación.","Cuatro pasos numerados con ecuaciones y control de unidades.","TEX 4.5–4.10 y storyboard U04-039/110/120."],
].map(([id,num,slug,klass,caption,alt,source])=>({id,num,slug,klass,caption,alt,source,stem:`u04_fig_${String(num).padStart(3,"0")}_${slug}`}));

function node(id,x,y,w,h,text,fill=C.white,border=C.bordo,fs=24,bold=false){return {id,x,y,w,h,text,fill,border,fs,bold,kind:"node"};}
function anchor(id,x,y){return {id,x,y,w:4,h:4,text:"",fill:"none",border:"none",fs:22,bold:false,kind:"anchor"};}
function edge(from,to,label="",color=C.gray,fromSide="right",toSide="left",kind="straight"){return {from,to,label,color,fromSide,toSide,kind};}
function text(id,x,y,w,h,value,fs=24,color=C.carbon,bold=false,align="center",fill="none"){return {id,x,y,w,h,text:value,fs,color,bold,align,fill,kind:"text"};}
function base(meta){return {meta,nodes:[],edges:[],texts:[],note:"",notScale:false};}

function chain(meta, labels, options={}){
  const s=base(meta), rows=options.rows||1, per=Math.ceil(labels.length/rows), w=options.w||200, h=options.h||108;
  const y0=options.y||250, rowGap=options.rowGap||210;
  labels.forEach((lab,i)=>{const r=Math.floor(i/per), c=i%per, count=Math.min(per,labels.length-r*per); const gap=(1120-count*w)/(Math.max(1,count-1)); const x=80+c*(w+gap); const y=y0+r*rowGap; s.nodes.push(node(`${meta.id}-N${i+1}`,x,y,w,h,lab,i%2?C.ivory:C.tealL,i%2?C.bordo:C.teal,options.fs||24));});
  for(let i=0;i<labels.length-1;i++){if(Math.floor(i/per)===Math.floor((i+1)/per))s.edges.push(edge(`${meta.id}-N${i+1}`,`${meta.id}-N${i+2}`,options.edgeLabels?.[i]||"",options.edgeColors?.[i]||C.gray));}
  if(rows>1){for(let r=0;r<rows-1;r++){const a=Math.min((r+1)*per,labels.length),b=a+1;if(b<=labels.length)s.edges.push(edge(`${meta.id}-N${a}`,`${meta.id}-N${b}`,"",C.gray,"bottom","top","elbow"));}}
  return s;
}

function equation(meta, eq, calls, bottom=[]){
  const s=base(meta); s.nodes.push(node(`${meta.id}-EQ`,330,245,620,128,eq,C.white,C.bordo,40,true),anchor(`${meta.id}-A1`,575,252),anchor(`${meta.id}-A2`,705,252),anchor(`${meta.id}-A3`,510,365),anchor(`${meta.id}-A4`,785,365));
  const pos=[[75,85],[945,85],[75,450],[945,450]];
  calls.forEach((c,i)=>{const [x,y]=pos[i]; s.nodes.push(node(`${meta.id}-C${i+1}`,x,y,260,126,c,i<2?C.tealL:C.ocreL,i<2?C.teal:C.ocre,23)); const e=edge(`${meta.id}-C${i+1}`,`${meta.id}-A${i+1}`,"",i<2?C.teal:C.ocre,i<2?"bottom":"top",i<2?"top":"bottom","elbow"); e.noHead=true; s.edges.push(e);});
  bottom.forEach((b,i)=>s.nodes.push(node(`${meta.id}-B${i+1}`,350+i*310,490,280,100,b,C.ivory,C.gray,23)));
  return s;
}

function specs(){
  const M=Object.fromEntries(metas.map(m=>[m.id,m])); const out=[];
  let s=chain(M["U04-DG-001"],["FUENTE\norigina la\nperturbación","MEDIO\nsostiene la\npropagación","MEDICIÓN\nestima en\nun punto","RECEPTOR\ndetecta o\npercibe"],{w:220,h:135,edgeLabels:["perturba","se propaga","responde"]});
  s.texts.push(text("q1",90,110,250,40,"¿qué varía?",22,C.bordo,true),text("q2",365,460,250,40,"¿qué se mueve?",22,C.teal,true),text("q3",635,110,250,40,"¿qué fluye?",22,C.ocre,true),text("q4",900,460,250,40,"¿qué se mide?",22,C.bordo,true),text("q5",510,590,300,40,"¿qué se percibe?",22,C.ocre,true)); out.push(s);
  s=chain(M["U04-DG-002"],["Fenómeno","Medio","Campo","Energía","Valores","RMS","Niveles","Suma","Geometría","Distancia y\ndirectividad","Aplicación"],{rows:3,w:220,h:100,y:105,rowGap:215,fs:23}); out.push(s);
  s=base(M["U04-DG-003"]); s.nodes.push(node("phys",80,95,520,150,"FENÓMENO FÍSICO\nCampo medible sin oyente",C.tealL,C.teal,26,true),node("perc",680,95,520,150,"EXPERIENCIA PERCEPTUAL\nRespuesta del sistema auditivo",C.ocreL,C.ocre,26,true)); ["Fuente","Medio","Campo","Receptor"].forEach((v,i)=>s.nodes.push(node(`c${i}`,110+i*280,385,210,100,v,i<3?C.tealL:C.ocreL,i<3?C.teal:C.ocre,25,true))); s.edges.push(edge("c0","c1","perturba",C.teal),edge("c1","c2","sostiene",C.teal),edge("c2","c3","responde",C.ocre)); s.texts.push(text("sum",250,565,780,55,"Medir el campo no equivale a describir una sensación.",25,C.bordo,true)); out.push(s);
  s=base(M["U04-DG-004"]); ["Flujo pulmonar","Pliegues vocales","Perturbación\naérea","Campo acústico"].forEach((v,i)=>s.nodes.push(node(`v${i}`,70+i*300,145,230,105,v,C.ocreL,C.ocre,23))); ["Señal eléctrica","Diafragma","Perturbación\naérea","Campo acústico"].forEach((v,i)=>s.nodes.push(node(`e${i}`,70+i*300,425,230,105,v,C.tealL,C.teal,23))); for(let i=0;i<3;i++){s.edges.push(edge(`v${i}`,`v${i+1}`,["excita","oscila","perturba"][i],C.ocre)); s.edges.push(edge(`e${i}`,`e${i+1}`,["excita","oscila","perturba"][i],C.teal));} s.texts.push(text("voice",70,85,300,40,"GENERACIÓN VOCAL",24,C.ocre,true,"left"),text("speaker",70,365,400,40,"GENERACIÓN ELECTROACÚSTICA",24,C.teal,true,"left")); out.push(s);
  s=chain(M["U04-DG-005"],["Compresión\nlocal","Fuerza\nrestauradora","Movimiento\nlocal","Nueva\ncompresión\nvecina","Avance del\nfrente"],{w:190,h:135,y:240,fs:24,edgeColors:[C.bordo,C.teal,C.bordo,C.gray]}); s.notScale=true; s.texts.push(text("legend",190,470,900,55,"bordó: fuerza · teal: movimiento local · gris: propagación",22,C.carbon,false)); out.push(s);
  s=equation(M["U04-DG-006"],"c = √(Kₛ / ρ)",["Kₛ ↑\nmayor rigidez","ρ ↑\nmayor inercia","Fluido homogéneo\npequeñas\nperturbaciones","No comparar medios\ncon una sola\nvariable"],["Medio 1\nf fija · c₁ · λ₁","Medio 2\nf fija · c₂ · λ₂"]); s.texts.push(text("lam",470,610,340,45,"λ = c / f",32,C.bordo,true)); out.push(s);
  s=base(M["U04-DG-007"]); s.nodes.push(node("field",65,140,350,380,"CAMPO ACÚSTICO\n\np(r,t)\nu(r,t)\nI(r,t)\n\nDos puntos pueden tener\nvalores diferentes.",C.tealL,C.teal,24),node("press",465,140,350,380,"PRESIÓN ACÚSTICA\n\np_total = p₀ + p\n\np > 0: sobrepresión\np < 0: rarefacción\n\np_total sigue positiva.",C.white,C.bordo,24),node("speed",865,140,350,380,"DOS VELOCIDADES\n\nu: movimiento local\nc: avance de la onda\n\nAmbas: m/s\nNo son la misma magnitud.",C.ocreL,C.ocre,24)); out.push(s);
  s=base(M["U04-DG-008"]); s.nodes.push(node("m1",65,140,430,340,"MEDIO 1\nZ₀₁\n\nonda incidente →\n← onda reflejada",C.tealL,C.teal,26,true),node("int",510,115,100,390,"",C.ivory,C.bordo,22,true),node("m2",625,140,590,340,"MEDIO 2\nZ₀₂\n\nonda transmitida →",C.ocreL,C.ocre,26,true)); s.edges.push(edge("m1","int","incidente",C.teal),edge("int","m2","transmitida",C.ocre)); s.texts.push(text("intLabel",485,68,150,35,"INTERFAZ",22,C.bordo,true),text("eqz",165,530,360,48,"Z₀ = p/u = ρc",32,C.teal,true),text("eqr",610,530,520,48,"Rₚ = (Z₀₂−Z₀₁)/(Z₀₂+Z₀₁)",31,C.bordo,true),text("note",350,610,580,35,"Longitud de flecha no representa amplitud.",20,C.gray)); s.notScale=true; out.push(s);
  s=equation(M["U04-DG-009"],"i(t) = p(t) · u(t)",["p en Pa\npresión local","u en m/s\nmovimiento local","i en W/m²\nel signo da\ndirección","I: promedio en Δt\nventana declarada"]); s.nodes.push(node("rms",335,480,610,116,"Onda plana progresiva\nI = pᵣₘₛ² / Z₀",C.ivory,C.gray,30,true)); out.push(s);
  s=chain(M["U04-DG-010"],["Intensidad I\nW/m²","Superficie S\nm²","Potencia\nW_ac (W)","Intervalo Δt\ns","Energía E_ac\nJ"],{w:190,h:110,y:260,fs:24,edgeLabels:["× S","","× Δt",""]}); s.texts.push(text("eq1",310,450,250,45,"W_ac = I·S",30,C.teal,true),text("eq2",720,450,280,45,"E_ac = W_ac·Δt",30,C.bordo,true)); out.push(s);
  s=base(M["U04-DG-011"]); const desc=[["Instantáneo","valor en t₁"],["Pico","máximo |p|"],["Pico a pico","p_max − p_min"],["Media","promedio algebraico"],["RMS","tamaño eficaz"]]; desc.forEach((d,i)=>{const col=i%3,row=Math.floor(i/3); s.nodes.push(node(`d${i}`,95+col*390,145+row*230,320,140,`${d[0]}\n${d[1]}`,i===4?C.ocreL:C.tealL,i===4?C.ocre:C.teal,24,i===4));}); s.texts.push(text("choose",310,595,660,42,"Elegir el descriptor según la pregunta y la ventana.",24,C.bordo,true)); out.push(s);
  s=chain(M["U04-DG-012"],["1 · CUADRAR\nPa → Pa²","2 · PROMEDIAR\nmedia de p²","3 · RAÍZ\nPa² → Pa"],{w:300,h:145,y:230,fs:26,edgeLabels:["elimina el signo","recupera la unidad"]}); s.texts.push(text("rmsEq",370,470,540,55,"pᵣₘₛ = √(media de p²)",34,C.bordo,true),text("sin",410,550,460,42,"pico/√2: solo para una senoide",22,C.ocre,true)); out.push(s);
  s=base(M["U04-DG-013"]); [["Lₚ","presión / p_ref","20 log₁₀"],["Lᵢ","intensidad / I_ref","10 log₁₀"],["L_W","potencia / W_ref","10 log₁₀"]].forEach((v,i)=>s.nodes.push(node(`l${i}`,85+i*405,135,330,150,`${v[0]}\n${v[1]}\n${v[2]}`,i===0?C.tealL:C.ivory,i===0?C.teal:C.bordo,25,true))); s.nodes.push(node("rule",340,370,600,110,"RAZÓN ADIMENSIONAL\nmagnitud y referencia de la misma clase",C.white,C.bordo,26,true)); s.edges.push(edge("l0","rule","",C.teal,"bottom","top","elbow"),edge("l1","rule","",C.bordo,"bottom","top","elbow"),edge("l2","rule","",C.bordo,"bottom","top","elbow")); s.texts.push(text("compare",205,545,870,50,"dB SPL ≠ dB HL ≠ sonoridad",28,C.ocre,true)); out.push(s);
  s=base(M["U04-DG-014"]); s.nodes.push(node("start",440,80,400,110,"¿Qué relación\ntemporal tienen?",C.white,C.bordo,26,true),node("coh",95,255,420,130,"COHERENTES\nfase estable",C.tealL,C.teal,25,true),node("unc",765,255,420,130,"NO CORRELACIONADAS\ntérmino cruzado\npromedia a cero",C.ocreL,C.ocre,24,true),node("cohr",95,490,420,115,"Sumar presiones\nen fase: +6,02 dB",C.white,C.teal,25,true),node("uncr",765,490,420,115,"Sumar cuadrados RMS\niguales: +3,01 dB",C.white,C.ocre,25,true)); s.edges.push(edge("start","coh","fase estable",C.teal,"left","top","elbow"),edge("start","unc","sin correlación",C.ocre,"right","top","elbow"),edge("coh","cohr","conservar término cruzado",C.teal,"bottom","top"),edge("unc","uncr","sumar energías",C.ocre,"bottom","top")); s.edges[0].labelPos={x:360,y:205}; s.edges[1].labelPos={x:820,y:205}; s.edges[2].labelPos={x:330,y:425}; s.edges[3].labelPos={x:790,y:425}; out.push(s);
  s=base(M["U04-DG-015"]); [["PLANO","área constante","I ∝ r⁰"],["CILÍNDRICO","área ∝ r","I ∝ r⁻¹"],["ESFÉRICO","área ∝ r²","I ∝ r⁻²"]].forEach((v,i)=>s.nodes.push(node(`g${i}`,70+i*400,105,340,170,v.join("\n"),i===1?C.tealL:C.white,i===1?C.teal:C.bordo,26,true))); [["Campo libre","onda directa domina"],["Campo próximo","modelo lejano no vale"],["Reverberante","reflexiones importantes"]].forEach((v,i)=>s.nodes.push(node(`f${i}`,70+i*400,410,340,125,v.join("\n"),C.ivory,C.gray,23))); s.texts.push(text("sep",330,600,620,42,"Geometría del frente ≠ tipo de campo",25,C.ocre,true)); s.notScale=true; out.push(s);
  s=base(M["U04-DG-016"]); s.nodes.push(node("src",80,260,170,120,"FUENTE\npuntual",C.ocreL,C.ocre,25,true),node("r1",310,170,220,100,"Superficie 1\nA₁=4πr₁²",C.tealL,C.teal,24),node("r2",310,390,220,100,"Superficie 2\nA₂=4πr₂²",C.tealL,C.teal,24)); s.edges.push(edge("src","r1","r₁",C.gray,"right","left"),edge("src","r2","r₂",C.gray,"right","left")); ["A ∝ r²","I ∝ 1/r²","pᵣₘₛ ∝ 1/r","ΔLₚ=20log₁₀(r₁/r₂)"].forEach((v,i)=>s.nodes.push(node(`step${i}`,650,95+i*135,490,92,`${i+1} · ${v}`,i===3?C.ocreL:C.white,i===3?C.ocre:C.bordo,i===3?28:25,i===3))); for(let i=0;i<3;i++)s.edges.push(edge(`step${i}`,`step${i+1}`,"",C.gray,"bottom","top")); s.notScale=true; out.push(s);
  s=base(M["U04-DG-017"]); s.nodes.push(node("omni",75,170,330,250,"OMNIDIRECCIONAL\nreferencia ideal\nmisma potencia total",C.tealL,C.teal,26,true),node("dir",475,170,330,250,"DIRECCIONAL\nredistribuye\nenergía\nsegún ángulo\ny frecuencia",C.ocreL,C.ocre,26,true),node("idx",875,170,330,250,"CUANTIFICAR\nQ_dir =\nI_dir / I_omni\nDI = 10log₁₀(Q_dir)",C.white,C.bordo,26,true)); s.edges.push(edge("omni","dir","igual W y r",C.gray),edge("dir","idx","comparar",C.gray)); s.texts.push(text("freq",260,520,760,50,"Siempre indicar dirección, frecuencia y condiciones.",24,C.bordo,true)); s.notScale=true; out.push(s);
  s=chain(M["U04-DG-018"],["Fuente","Campo en\nun punto","Sensor\ncalibrado","Procesamiento\nRMS/ajustes","Nivel con\nreferencia","Informe con\ncondiciones"],{rows:2,w:280,h:105,y:145,rowGap:315,fs:23,edgeLabels:["origina","mide","procesa","expresa","interpreta"]}); out.push(s);
  s=base(M["U04-DG-019"]); const errs=[["u = c","movimiento local ≠ propagación"],["media cero = señal nula","RMS puede ser distinto de cero"],["RMS = pico/√2 siempre","solo vale para una senoide"],["sumar dB aritméticamente","sumar magnitudes según el caso"],["−6 dB siempre","solo bajo modelo esférico válido"],["reverberante = difuso","difuso requiere más condiciones"],["dB = sonoridad","nivel físico ≠ percepción"]]; errs.forEach((v,i)=>{const left=i<4,x=left?65:655,row=left?i:i-4; s.nodes.push(node(`e${i}`,x,70+row*150,560,120,`ERROR: ${v[0]}\nCORRECCIÓN: ${v[1]}`,i%2?C.ivory:C.white,i%2?C.bordo:C.teal,22,false));}); out.push(s);
  s=base(M["U04-DG-020"]); s.nodes.push(node("src",70,235,250,150,"FUENTE\nQ o DI declarado",C.ocreL,C.ocre,25,true),node("p1",390,110,220,130,"Punto 1\nr₁\ndirección 1",C.tealL,C.teal,23),node("p2",390,390,220,130,"Punto 2\nr₂\ndirección 2",C.tealL,C.teal,23)); s.edges.push(edge("src","p1","r₁ / ángulo 1",C.gray),edge("src","p2","r₂ / ángulo 2",C.gray)); ["1 · ΔL_r\n20log₁₀(r₁/r₂)","2 · ΔDI\nmisma referencia","3 · ΔL_total\nΔL_r + ΔDI"].forEach((v,i)=>s.nodes.push(node(`calc${i}`,730,105+i*185,430,120,v,i===2?C.ocreL:C.white,i===2?C.ocre:C.bordo,i===2?28:25,i===2))); for(let i=0;i<2;i++)s.edges.push(edge(`calc${i}`,`calc${i+1}`,"",C.gray,"bottom","top")); out.push(s);
  s=base(M["U04-DG-021"]); s.nodes.push(node("pre",60,110,360,490,"PRERREQUISITOS\n\nPa · W · J · m/s\nc=λf\nfase y superposición\nrazones y logaritmos",C.white,C.bordo,23),node("gen",460,110,360,490,"MECANISMOS\n\nmembrana\ncuerda\npliegues vocales\ncolumna de aire\nturbulencia",C.tealL,C.teal,23),node("rms",860,110,360,490,"CHECKLIST RMS\n\nseñal\nventana\noperación\nunidad\n¿es senoide?",C.ocreL,C.ocre,23)); out.push(s);
  s=chain(M["U04-DG-022"],["1 · DATOS\n0,20 Pa RMS\nZ₀=400 Pa·s/m","2 · RELACIÓN\nuᵣₘₛ = pᵣₘₛ/Z₀","3 · CÁLCULO\n5,0×10⁻⁴ m/s","4 · VERIFICAR\nunidad y\ncondición"],{w:240,h:145,y:220,fs:24,edgeLabels:["elegir","sustituir","interpretar"]}); s.texts.push(text("cond",300,500,680,55,"Onda plana progresiva · medio homogéneo · sin pérdidas",22,C.ocre,true)); out.push(s);
  return out;
}

function addFrame(slide,n){
  return slide.shapes.add({geometry:"rect",name:`${n.id}-frame`,position:{left:n.x,top:n.y,width:n.w,height:n.h},fill:n.fill,line:{style:"solid",fill:n.border,width:2},borderRadius:6});
}
function addTextbox(slide,n){
  const inset=n.kind==="node"?18:0; const sh=slide.shapes.add({geometry:"textbox",name:`${n.id}-text`,position:{left:n.x+inset,top:n.y+inset,width:n.w-2*inset,height:n.h-2*inset},fill:n.fill||"none",line:{style:"solid",fill:"none",width:0}}); sh.text=n.text; sh.text.style={fontSize:n.fs||24,bold:!!n.bold,color:n.color||C.carbon,alignment:n.align||"center",fontFamily:n.fs>=30?"Cambria Math":"Calibri"}; return sh;
}
function addSlide(pres,spec){
  const slide=pres.slides.add(); slide.background.fill=C.white;
  const frames=new Map(); for(const n of spec.nodes)frames.set(n.id,addFrame(slide,n));
  for(const e of spec.edges){const conn=slide.shapes.connect(frames.get(e.from),frames.get(e.to),{kind:e.kind||"straight",fromSide:e.fromSide||"right",toSide:e.toSide||"left",line:{style:"solid",fill:e.color||C.gray,width:2.5},head:{type:"none"},tail:{type:e.noHead?"none":"triangle",width:"sm",length:"sm"}}); conn.name=`${spec.meta.id}-edge-${e.from}-${e.to}`;}
  for(const n of spec.nodes)if(n.kind!=="anchor")addTextbox(slide,n);
  for(const e of spec.edges){if(!e.label)continue; const a=spec.nodes.find(n=>n.id===e.from),b=spec.nodes.find(n=>n.id===e.to); const cx=(a.x+a.w+b.x)/2, cy=(a.y+a.h/2+b.y+b.h/2)/2; let x=cx-85,y=cy-48; if(e.fromSide==="bottom"&&e.toSide==="top"){x=cx+20;y=cy-15;} if(e.labelPos){x=e.labelPos.x;y=e.labelPos.y;} addTextbox(slide,text(`${spec.meta.id}-label-${e.from}-${e.to}`,x,y,170,30,e.label,21,e.color||C.gray,true,"center",C.white));}
  for(const t of spec.texts)addTextbox(slide,t);
  if(spec.notScale)addTextbox(slide,text(`${spec.meta.id}-scale`,1010,652,205,28,"FIGURA NO A ESCALA",18,C.gray,true,"right"));
  slide.speakerNotes.textFrame.setText(`[Sources]\n- ${spec.meta.source}\n[/Sources]\nCaption: ${spec.meta.caption}\nAlt: ${spec.meta.alt}`);
  return slide;
}

function esc(s){return String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function svgText(n){const lines=n.text.split("\n"),lh=(n.fs||24)*1.28,cy=n.y+n.h/2-(lines.length-1)*lh/2; return lines.map((ln,i)=>`<text x="${n.x+n.w/2}" y="${cy+i*lh}" text-anchor="middle" dominant-baseline="middle" font-family="${n.fs>=30?'Cambria Math':'Calibri,Arial,sans-serif'}" font-size="${n.fs||24}" font-weight="${n.bold?700:400}" fill="${n.color||C.carbon}">${esc(ln)}</text>`).join("\n");}
function sidePoint(n,side){if(side==="left")return [n.x,n.y+n.h/2]; if(side==="right")return [n.x+n.w,n.y+n.h/2]; if(side==="top")return [n.x+n.w/2,n.y]; return [n.x+n.w/2,n.y+n.h];}
function toSvg(spec){let z=`<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="context-stroke"/></marker></defs><rect width="1280" height="720" fill="#fff"/>`;
  for(const e of spec.edges){const a=spec.nodes.find(n=>n.id===e.from),b=spec.nodes.find(n=>n.id===e.to),p=sidePoint(a,e.fromSide||"right"),q=sidePoint(b,e.toSide||"left"); z+=`<line x1="${p[0]}" y1="${p[1]}" x2="${q[0]}" y2="${q[1]}" stroke="${e.color||C.gray}" stroke-width="3" ${e.noHead?'':'marker-end="url(#arrow)"'}/>`;}
  for(const n of spec.nodes)if(n.kind!=="anchor")z+=`<rect x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="6" fill="${n.fill}" stroke="${n.border}" stroke-width="2"/>`;
  for(const n of spec.nodes)if(n.kind!=="anchor")z+=svgText({...n,color:C.carbon});
  for(const e of spec.edges){if(!e.label)continue; const a=spec.nodes.find(n=>n.id===e.from),b=spec.nodes.find(n=>n.id===e.to),cx=(a.x+a.w+b.x)/2,cy=(a.y+a.h/2+b.y+b.h/2)/2; let x=cx-85,y=cy-48;if(e.fromSide==="bottom"&&e.toSide==="top"){x=cx+20;y=cy-15;}if(e.labelPos){x=e.labelPos.x;y=e.labelPos.y;}z+=`<rect x="${x-3}" y="${y-3}" width="176" height="36" fill="#fff"/>`+svgText(text("",x,y,170,30,e.label,21,e.color||C.gray,true));}
  for(const t of spec.texts)z+=svgText(t); if(spec.notScale)z+=svgText(text("",1010,652,205,28,"FIGURA NO A ESCALA",18,C.gray,true)); return z+"</svg>";
}

function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
function validate(spec){const issues=[]; for(const n of spec.nodes){if(n.kind==="anchor")continue;if(n.x<48||n.y<48||n.x+n.w>1232||n.y+n.h>660)issues.push(`fuera de margen: ${n.id}`); if(n.fs<22)issues.push(`fuente menor a 22 pt: ${n.id}`); const lines=n.text.split("\n"),max=Math.max(...lines.map(x=>x.length)),cap=Math.floor((n.w-36)/(n.fs*.52)); if(max>cap)issues.push(`posible desborde horizontal: ${n.id} (${max}>${cap})`); if(lines.length*n.fs*1.28>n.h-36)issues.push(`posible desborde vertical: ${n.id}`);}
  for(let i=0;i<spec.nodes.length;i++)for(let j=i+1;j<spec.nodes.length;j++)if(spec.nodes[i].kind!=="anchor"&&spec.nodes[j].kind!=="anchor"&&overlap(spec.nodes[i],spec.nodes[j]))issues.push(`superposición de nodos: ${spec.nodes[i].id}/${spec.nodes[j].id}`);
  for(const e of spec.edges){if(!spec.nodes.some(n=>n.id===e.from)||!spec.nodes.some(n=>n.id===e.to))issues.push(`conector sin destino: ${e.from}->${e.to}`);}
  return {critical:0,major:issues.length,minor:0,issues,status:issues.length?"needs_fix":"approved"};
}

async function writeBlob(file,blob){await fs.writeFile(file,new Uint8Array(await blob.arrayBuffer()));}
async function main(){await fs.mkdir(OUT,{recursive:true}); const all=specs();
  if(process.env.VALIDATE_ONLY==="1"){let bad=0; for(const spec of all){const r=validate(spec); if(r.major){bad++; console.error(`${spec.meta.id}: ${r.issues.join("; ")}`);} else console.log(`${spec.meta.id}: OK`);} if(bad)process.exitCode=1; return;}
  const global=Presentation.create({slideSize:{width:W,height:H}}); const reports=[];
  for(let i=0;i<all.length;i++){
    const spec=all[i], d=path.join(OUT,spec.meta.id); await fs.mkdir(d,{recursive:true});
    const pre=validate(spec); if(pre.major)throw new Error(`${spec.meta.id}: ${pre.issues.join("; ")}`);
    const one=Presentation.create({slideSize:{width:W,height:H}}), slide=addSlide(one,spec); addSlide(global,spec);
    await writeBlob(path.join(d,`${spec.meta.stem}.png`),await one.export({slide,format:"png",scale:2}));
    await fs.writeFile(path.join(d,`${spec.meta.stem}.svg`),toSvg(spec),"utf8");
    await fs.writeFile(path.join(d,`${spec.meta.stem}.layout.json`),await (await slide.export({format:"layout"})).text(),"utf8");
    const pptx=await PresentationFile.exportPptx(one); await pptx.save(path.join(d,`${spec.meta.stem}_editable.pptx`));
    const report={id:spec.meta.id,classification:spec.meta.klass,iteration_1:"generado y validado geométricamente",iteration_2:"render PNG 2560×1440 inspeccionable en canvas 16:9",...pre,objects:spec.nodes.length+spec.edges.length+spec.texts.length,minimum_main_font_pt:Math.min(...spec.nodes.map(n=>n.fs)),connector_labels_min_pt:21,editable:true};
    await fs.writeFile(path.join(d,"validation.json"),JSON.stringify(report,null,2),"utf8");
    await fs.writeFile(path.join(d,"README.md"),`# ${spec.meta.id} — ${spec.meta.slug.replaceAll("_"," ")}\n\n- Clasificación: ${spec.meta.klass}.\n- Skill: \`diagram-generation\`.\n- Fuente editable: \`${spec.meta.stem}_editable.pptx\` (formas, textos y conectores nativos).\n- Respaldo vectorial: \`${spec.meta.stem}.svg\`.\n- Respaldo raster: \`${spec.meta.stem}.png\` (2560×1440).\n- Caption sugerido: ${spec.meta.caption}\n- Texto alternativo: ${spec.meta.alt}\n- Fuente conceptual: ${spec.meta.source}\n- Escala: ${spec.notScale?"figura conceptual no a escala.":"no corresponde; relaciones cualitativas."}\n- Validación: cero problemas críticos o mayores en la comprobación geométrica previa; ver \`validation.json\`.\n`,"utf8"); reports.push(report);
  }
  const deck=await PresentationFile.exportPptx(global); await deck.save(path.join(OUT,"u04_diagram_assets_editables.pptx")); await fs.writeFile(path.join(OUT,"validation_summary.json"),JSON.stringify(reports,null,2),"utf8");
}
main().catch(e=>{console.error(e);process.exitCode=1;});
