/** Genera, renderiza y valida los diagramas editables aprobados de U07. */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const UNIT_DIR = path.dirname(SCRIPT_DIR);
const ROOT = path.join(UNIT_DIR, "assets", "generated", "diagrams");
const artifactWorkspace = process.env.U07_ARTIFACT_WORKSPACE;
if (!artifactWorkspace) throw new Error("Definir U07_ARTIFACT_WORKSPACE con un workspace inicializado para @oai/artifact-tool");
const workspaceRequire = createRequire(path.join(path.resolve(artifactWorkspace), "package.json"));
const artifactEntry = workspaceRequire.resolve("@oai/artifact-tool");
const { Presentation, PresentationFile } = await import(pathToFileURL(artifactEntry).href);

const C = { bordo:"#4D1434", bordo2:"#903163", teal:"#2F7E83", carbon:"#3D3D3D", gris:"#969FA7", gris2:"#D9DCE0", marfil:"#F7F6F2", fisico:"#E7F1F1", ocre:"#9F541A", clinico:"#F8EDE2", blanco:"#FFFFFF", error:"#A33A3A", ok:"#2F6F55", bordoFill:"#F3E8EE" };
const W=1280, H=720;
const SOURCE="Libro del curso (TEX/PDF), Unidad 7; brief, storyboard y planes U07; elaboración propia UCASAL.";
const FOOTER="Figura conceptual; no está a escala salvo indicación explícita.";

const item=(title,body="",style="neutral")=>({title,body,style});
const spec=(id,classification,title,template,items,caption,alt,options={})=>({id,classification,title,template,items,caption,alt,source:SOURCE,footer:options.footer??FOOTER,options});

const SPECS = [
  spec("U07-DG-001","diagrama de proceso","Del campo físico a una respuesta observable","flow",[item("Campo acústico","estímulo","physical"),item("Oído periférico","transforma","accent"),item("Tarea","define qué observar","neutral"),item("Respuesta","se registra","clinical")],"Puente funcional entre la Unidad 6 y la psicofísica de la Unidad 7.","Cuatro etapas conectadas de izquierda a derecha: campo acústico, oído periférico, tarea y respuesta registrada.",{labels:["transfiere","condiciona","se registra"]}),
  spec("U07-DG-002","diagrama conceptual","Una magnitud física no es su correlato perceptual","grid",[item("Frecuencia, f","Hz","physical"),item("Altura tonal","respuesta perceptual","clinical"),item("Nivel, L_p","dB SPL","physical"),item("Sonoridad","fon o son","clinical"),item("Espectro","amplitud y frecuencia","physical"),item("Timbre","atributo perceptual","clinical"),item("Tiempo","s o ms","physical"),item("Duración percibida","respuesta temporal","clinical")],"Matriz físico–perceptual con unidades como evidencia de que las cantidades no son intercambiables.","Cuatro pares relacionan frecuencia y altura tonal, nivel y sonoridad, espectro y timbre, tiempo y duración percibida."),
  spec("U07-DG-003","diagrama de proceso","La unidad avanza por cuatro preguntas perceptuales","flow",[item("Umbral y campo","¿se detecta?","physical"),item("Atributos","¿cómo se percibe?","clinical"),item("Dificultad","¿qué interfiere?","accent"),item("Espacio y escena","¿qué fuente?","clinical")],"Mapa de los cuatro grandes encuentros de la Unidad 7.","Cuatro macroetapas conectadas: umbral, atributos, dificultad perceptual y escena espacial."),
  spec("U07-DG-004","diagrama de proceso","La medición psicofísica une estímulo, tarea y respuesta","flow",[item("Estímulo","señal y condiciones","physical"),item("Tarea","detectar · igualar · estimar","accent"),item("Respuesta","criterio observable","clinical"),item("Contexto","oyente · ambiente · método","neutral")],"Marco operativo para interpretar cualquier resultado psicofísico.","Cadena de estímulo, tarea y respuesta con una cuarta caja que recuerda el contexto del procedimiento."),
  spec("U07-DG-005","diagrama de proceso","Un mismo estímulo admite tareas diferentes","branch",[item("Estímulo controlado","se presenta","physical"),item("Detectar","sí / no","clinical"),item("Igualar","más / menos","clinical"),item("Estimar","número o categoría","clinical")],"Tres tareas psicofísicas alternativas nacen de un estímulo controlado.","Una caja de estímulo se bifurca sin cruces hacia tareas de detección, igualación y estimación."),
  spec("U07-DG-006","diagrama conceptual","Un dato psicofísico necesita sus condiciones","branch",[item("Resultado observado","valor + unidad","accent"),item("Señal","frecuencia · duración","physical"),item("Nivel","referencia · banda","physical"),item("Tarea","criterio","neutral"),item("Ambiente","ruido · recinto","neutral"),item("Oyente","estado · experiencia","clinical"),item("Procedimiento","orden · repeticiones","clinical")],"Seis condiciones delimitan el alcance de un resultado psicofísico.","Un resultado central se relaciona con señal, nivel, tarea, ambiente, oyente y procedimiento."),
  spec("U07-DG-007","esquema mixto","Campo libre: fuente, dirección y punto de referencia","flow",[item("Fuente","emite","physical"),item("Propagación","dirección definida","physical"),item("Punto de campo","L_p,campo","accent")],"Geometría mínima para definir una medición de campo sin oyente.","Fuente, dirección de propagación y punto de campo conectados horizontalmente; el esquema declara que no está a escala."),
  spec("U07-DG-008","diagrama de proceso","La presión cambia entre el campo y el tímpano","flow",[item("Campo de referencia","L_p,campo","physical"),item("Cabeza y pabellón","dirección y geometría","neutral"),item("CAE","depende de frecuencia","accent"),item("Tímpano","L_p,T","clinical")],"Cadena de transferencia desde una referencia de campo hasta la presión próxima al tímpano.","Cuatro etapas conectadas: campo, cabeza y pabellón, conducto auditivo externo y tímpano."),
  spec("U07-DG-009","ecuación anotada","G_CT compara dos posiciones de medición","equation",[item("G_CT(f) = L_p,T(f) − L_p,campo(f)","resultado en dB","equation"),item("L_p,T","nivel próximo al tímpano","clinical"),item("L_p,campo","nivel en el punto de campo","physical"),item("Condición común","misma f y procedimiento","neutral")],"Ecuación anotada de diferencia campo–tímpano.","Ecuación central G sub CT igual nivel en tímpano menos nivel de campo, con tres llamadas externas."),
  spec("U07-DG-009B","ecuación anotada","Ejemplo: entre 50 y 58 dB SPL hay una diferencia de 8 dB","flow",[item("Datos","campo: 50 dB SPL\ntímpano: 58 dB SPL","physical"),item("Resta","58 − 50","accent"),item("Resultado","G_CT = 8 dB","clinical"),item("Límite","no es sonoridad\nni ganancia universal","neutral")],"Cálculo de una diferencia campo–tímpano para una frecuencia y dos posiciones definidas.","Cuatro pasos: datos de cincuenta y cincuenta y ocho decibeles SPL, resta, resultado de ocho decibeles y límite interpretativo."),
  spec("U07-DG-011","diagrama de proceso","Cada punto isofónico surge de una comparación","flow",[item("Referencia","1 kHz","physical"),item("Tono de prueba","otra frecuencia","physical"),item("Ajuste","cambiar nivel","accent"),item("Juicio","igual sonoridad","clinical"),item("Punto","registrar y repetir","neutral")],"Proceso conceptual de construcción de una curva de igual sonoridad.","Cinco etapas conectadas: referencia de un kilohertz, tono de prueba, ajuste de nivel, juicio de igual sonoridad y registro del punto.",{labels:["comparar","ajustar","igualar","repetir"]}),
  spec("U07-DG-012","diagrama conceptual","Las magnitudes físicas se relacionan con atributos, no los igualan","grid",[item("Frecuencia","Hz","physical"),item("Altura tonal","grave ↔ agudo","clinical"),item("Nivel","dB SPL","physical"),item("Sonoridad","fon / son","clinical"),item("Espectro","componentes","physical"),item("Timbre","calidad perceptual","clinical"),item("Tiempo","s · ms","physical"),item("Duración","atributo temporal","clinical")],"Mapa de cuatro relaciones físico–perceptuales sin signos de igualdad.","Ocho celdas organizadas en cuatro pares de magnitud física y atributo perceptual."),
  spec("U07-DG-012B","diagrama conceptual","Una señal puede cambiar en más de una dimensión perceptual","branch",[item("Señal acústica","múltiples descriptores","physical"),item("Altura tonal","principalmente frecuencia","clinical"),item("Sonoridad","nivel + frecuencia + tiempo","clinical"),item("Timbre","espectro + tiempo","clinical"),item("Duración","estructura temporal","clinical")],"Enlaces secundarios recuerdan que las correspondencias no son uno a uno.","Una señal acústica central se relaciona con altura tonal, sonoridad, timbre y duración."),
  spec("U07-DG-013","diagrama conceptual","L_p, L_N y N_son responden preguntas distintas","grid",[item("L_p","nivel de presión\ndB SPL","physical"),item("L_N","nivel de sonoridad\nfon","accent"),item("N_son","sonoridad\nson","clinical"),item("Medir","presión referida","physical"),item("Igualar","con 1 kHz","accent"),item("Estimar razón","doble · mitad","clinical")],"Comparación entre nivel de presión, nivel de sonoridad y sonoridad.","Tres columnas conceptuales distinguen símbolos, unidades y operaciones: medir, igualar y estimar razón."),
  spec("U07-DG-014","diagrama de proceso","La referencia de 1 kHz conecta fones y sones","flow",[item("Tono de 1 kHz","nivel conocido","physical"),item("Igualar sonoridad","tarea","accent"),item("Asignar L_N","valor en fon","clinical"),item("Referencia de razón","40 fon ↔ 1 son","clinical")],"Construcción conceptual de las referencias de fon y son.","Cuatro etapas conectan tono de un kilohertz, igualdad de sonoridad, nivel en fones y referencia cuarenta fon equivalente a un son."),
  spec("U07-DG-015","ecuación anotada","La relación fones–sones usa un exponente adimensional","equation",[item("N_son = 2^[(L_N − 40 fon)/(10 fon)] son","válida aquí para L_N ≥ 40 fon","equation"),item("base 2","cada 10 fon duplica","accent"),item("L_N − 40 fon","distancia a la referencia","clinical"),item("10 fon","hace adimensional el exponente","neutral"),item("son","unidad del resultado","physical")],"Ecuación anotada del modelo introductorio entre fones y sones.","Ecuación central de sonoridad en sones con cuatro llamadas a base dos, referencia de cuarenta fon, denominador de diez fon y unidad son."),
  spec("U07-DG-015B","ecuación anotada","Ejemplo: 70 fon corresponden a 8 sones en el modelo","flow",[item("Dato","L_N = 70 fon","physical"),item("Exponente","(70−40)/10 = 3","accent"),item("Potencia","2³ = 8","accent"),item("Resultado","N_son = 8 sones","clinical")],"Cálculo paso a paso de la sonoridad del modelo para 70 fon.","Cuatro pasos convierten setenta fon en exponente tres, potencia dos al cubo y resultado ocho sones."),
  spec("U07-DG-016","diagrama conceptual","Tres niveles evitan una resta ambigua","branch",[item("Condición de medición","misma f_obj y procedimiento","accent"),item("L_umbral,q","umbral en quietud · dB SPL","physical"),item("L_enmascarador","nivel de la máscara · dB SPL","neutral"),item("L_umbral,e","umbral enmascarado · dB SPL","clinical")],"Mapa de los tres niveles usados al describir enmascaramiento.","Una condición común se bifurca hacia umbral en quietud, nivel del enmascarador y umbral enmascarado."),
  spec("U07-DG-017","ecuación anotada","M es una diferencia de umbrales","equation",[item("M(f_obj) = L_umbral,e(f_obj) − L_umbral,q(f_obj)","resultado en dB","equation"),item("L_umbral,e","con enmascarador","clinical"),item("L_umbral,q","en quietud","physical"),item("f_obj","misma frecuencia objetivo","neutral")],"Ecuación anotada de elevación del umbral por enmascaramiento.","Ecuación central M de la frecuencia objetivo igual umbral enmascarado menos umbral en quietud, con tres llamadas externas."),
  spec("U07-DG-017B","ecuación anotada","Ejemplo: el umbral sube 25 dB","flow",[item("Quietud","10 dB SPL","physical"),item("Con máscara","35 dB SPL","clinical"),item("Resta","35 − 10","accent"),item("Resultado","M = 25 dB","clinical")],"Cálculo de la elevación del umbral entre 10 y 35 dB SPL.","Cuatro pasos muestran umbral en quietud, umbral con máscara, resta y resultado de veinticinco decibeles."),
  spec("U07-DG-018","diagrama de proceso","Enmascaramiento simultáneo significa superposición temporal","timeline",[item("Objetivo","activo","physical"),item("Máscara","activa","accent"),item("Solapamiento","misma ventana temporal","clinical")],"Alternativa estática para mostrar la superposición temporal de objetivo y máscara.","Tres cuadros temporales muestran objetivo, máscara y su intervalo de solapamiento; las duraciones son esquemáticas."),
  spec("U07-DG-019","diagrama de proceso","Un banco de filtros distribuye el espectro en canales","branch",[item("Espectro de entrada","energía por frecuencia","physical"),item("Canal bajo","respuesta","neutral"),item("Canal medio","respuesta","accent"),item("Canal alto","respuesta","neutral")],"Banco conceptual de tres canales representativos.","Una entrada espectral se bifurca hacia canales auditivos bajo, medio y alto; tres canales representan un banco mayor."),
  spec("U07-DG-020","esquema mixto","ERB resume un filtro por igualdad de área","overlay",[item("Curva del filtro","respuesta normalizada","physical"),item("Misma altura","W_max","accent"),item("Misma área","integral equivalente","clinical"),item("Ancho","ERB","neutral")],"La curva U07-CH-008 se combina con llamadas editables para definir la anchura rectangular equivalente.","Gráfico de respuesta gaussiana y rectángulo equivalente con tres llamadas externas a altura, área y ancho.",{chart:"U07-CH-008/u07_fig_008_erb_igualdad_area.png"}),
  spec("U07-DG-020B","diagrama de proceso","El filtro es un modelo intermedio, no una decisión perceptual","flow",[item("Estímulo","espectro","physical"),item("Canal auditivo","pondera energía","accent"),item("Salida interna","depende de f_c y ancho","neutral"),item("Tarea","detectar o comparar","clinical")],"Cadena funcional desde estímulo hasta decisión mediante un canal auditivo conceptual.","Cuatro etapas conectan estímulo, canal auditivo, salida interna y tarea perceptual."),
  spec("U07-DG-021","diagrama de proceso","La máscara puede aparecer antes, durante o después del objetivo","timeline",[item("Hacia atrás","máscara antes del objetivo","neutral"),item("Simultáneo","se superponen","accent"),item("Hacia adelante","máscara después del objetivo","clinical")],"Comparación temporal de tres relaciones entre máscara y objetivo.","Tres cuadros alineados muestran enmascaramiento hacia atrás, simultáneo y hacia adelante con la misma escala visual."),
  spec("U07-DG-022A","diagrama de proceso","Enmascaramiento energético: la competencia comienza en canales","flow",[item("Objetivo + máscara","señales físicas","physical"),item("Canales solapados","energía compartida","accent"),item("Menor contraste","señal interna","neutral"),item("Respuesta","más errores","clinical")],"Ruta funcional del enmascaramiento energético.","Cuatro etapas conectan señales físicas, canales solapados, señal interna con menor contraste y respuesta."),
  spec("U07-DG-022B","diagrama de proceso","Enmascaramiento informacional: la dificultad está en seleccionar","flow",[item("Fuentes similares","objetivo + rival","physical"),item("Señales audibles","no basta oírlas","neutral"),item("Selección atencional","¿cuál seguir?","accent"),item("Respuesta","más errores","clinical")],"Ruta funcional del enmascaramiento informacional.","Cuatro etapas conectan fuentes similares, representaciones disponibles, selección atencional y respuesta."),
  spec("U07-DG-022C","diagrama conceptual","Dos mecanismos pueden coexistir","grid",[item("Competencia energética","solapamiento de canales","physical"),item("Competencia informacional","selección de fuente","clinical"),item("Pista espectral","separación física","neutral"),item("Pista espacial","separación de dirección","accent"),item("Tarea","qué hay que reconocer","neutral"),item("Oyente","audición y atención","clinical")],"Matriz de mecanismos y condiciones que pueden combinarse.","Seis celdas organizan competencia energética, informacional y cuatro moduladores."),
  spec("U07-DG-023","esquema mixto","Dos voces convergen en los oídos, pero compiten de modos distintos","branch",[item("Respuesta del oyente","seguir la voz objetivo","clinical"),item("Voz objetivo","ruta sólida + rótulo","physical"),item("Voz competidora","ruta discontinua + patrón","accent"),item("Atención","selecciona objeto","neutral")],"Escena conceptual de dos voces con rutas distinguibles por color, rótulo y patrón.","Una respuesta central se relaciona con voz objetivo, voz competidora y atención; las rutas no dependen solo del color."),
  spec("U07-DG-024","diagrama conceptual","La inteligibilidad pertenece a una prueba definida","grid",[item("Estímulo","lista · contexto · nivel","physical"),item("Procedimiento","consigna · respuesta · puntaje","accent"),item("Oyente","audición · lengua · experiencia","clinical"),item("Resultado","porcentaje correcto","clinical")],"Condiciones mínimas para interpretar un porcentaje de inteligibilidad.","Cuatro grupos organizan estímulo, procedimiento, oyente y resultado porcentual."),
  spec("U07-DG-025","ecuación anotada","La SNR compara niveles medidos en condiciones comunes","equation",[item("SNR = L_p,habla − L_p,ruido","resultado en dB","equation"),item("L_p,habla","señal de interés","physical"),item("L_p,ruido","interferencia","neutral"),item("signo","positivo: habla con mayor nivel","clinical"),item("Comparabilidad","misma banda · punto · intervalo","accent")],"Ecuación anotada de relación señal–ruido.","Ecuación central SNR igual nivel de habla menos nivel de ruido, con cuatro llamadas externas."),
  spec("U07-DG-025B","ecuación anotada","Ejemplo: 68 dB SPL de voz y 60 dB SPL de ruido","flow",[item("Habla","68 dB SPL","physical"),item("Ruido","60 dB SPL","neutral"),item("Resta","68 − 60","accent"),item("Resultado","SNR = +8 dB\nno predice % correcto","clinical")],"Cálculo e interpretación limitada de una SNR de más ocho decibeles.","Cuatro pasos muestran nivel de habla, nivel de ruido, resta y resultado positivo con advertencia."),
  spec("U07-DG-026","esquema mixto","Las colas reverberantes superponen segmentos del habla","timeline",[item("Sílaba 1","directo + cola","physical"),item("Sílaba 2","se suma a la cola","accent"),item("Sílaba 3","transiciones cubiertas","clinical")],"Alternativa estática de tres sílabas con colas temporales que se superponen.","Tres cuadros temporales muestran sílabas sucesivas y colas crecientes; el esquema no codifica tiempos reales."),
  spec("U07-DG-026B","diagrama de proceso","Ruido y reverberación degradan información por vías distintas","branch",[item("Reconocimiento de habla","resultado condicionado","clinical"),item("Ruido","compite con la señal","physical"),item("Reverberación","redistribuye energía en el tiempo","accent"),item("Interacción","puede agravar la competencia","neutral")],"Mapa causal cualitativo de ruido, reverberación e inteligibilidad.","Ruido, reverberación e interacción convergen en un resultado de reconocimiento de habla."),
  spec("U07-DG-027","esquema mixto","T₆₀ describe un intervalo de decaimiento de 60 dB","overlay",[item("Decaimiento","CH-009","physical"),item("Inicio","0 dB relativo","accent"),item("−60 dB","cambio de nivel","clinical"),item("T₆₀","intervalo de tiempo","neutral")],"La curva U07-CH-009 recibe llamadas editables a inicio, menos sesenta decibeles e intervalo T sesenta.","Gráfico de decaimiento con tres llamadas editables que señalan el inicio, la caída de sesenta decibeles y el intervalo T sesenta.",{chart:"U07-CH-009/u07_fig_009_decaimiento_t60.png"}),
  spec("U07-DG-028","ecuación anotada","ALCons es un porcentaje observado","equation",[item("ALCons = 100 · (1 − n_c / n_p) %","conteos de una prueba definida","equation"),item("n_p","consonantes presentadas","physical"),item("n_c","consonantes correctas","clinical"),item("100 ×","convierte la proporción en %","accent"),item("Límite","no identifica la causa","neutral")],"Ecuación anotada de pérdida de articulación de consonantes.","Ecuación central ALCons igual cien por uno menos correctas sobre presentadas, con cuatro llamadas externas."),
  spec("U07-DG-028B","diagrama de proceso","Señal, ambiente, tarea y oyente preceden al porcentaje","flow",[item("Señal","habla + ruido","physical"),item("Ambiente","ruido + reflexiones","neutral"),item("Tarea y oyente","material + respuesta","accent"),item("Resultado","porcentaje observado","clinical")],"Síntesis del bloque de inteligibilidad sin reducirlo a SNR o T₆₀.","Cuatro etapas conectan señal, ambiente, tarea y oyente, y resultado observado."),
  spec("U07-DG-029","esquema mixto","El camino reflejado es más largo que el directo","spatial",[item("Fuente","emite","physical"),item("Superficie","refleja","neutral"),item("Oyente","recibe dos llegadas","clinical"),item("Camino directo","r_d · línea sólida","accent"),item("Camino reflejado","r_r · línea discontinua","physical")],"Geometría conceptual de recorridos directo y reflejado.","Fuente, superficie y oyente con dos recorridos visualmente distintos y rótulos r sub d y r sub r.",{spatialMode:"out"}),
  spec("U07-DG-030","ecuación anotada","El retardo depende de la diferencia de recorridos","equation",[item("Δt = (r_r − r_d) / c","segundos = metros / (metros por segundo)","equation"),item("r_r − r_d","diferencia de camino · m","physical"),item("c","rapidez del sonido · m/s","accent"),item("Δt","retardo de llegada · s","clinical")],"Ecuación anotada del retardo entre llegada reflejada y directa.","Ecuación central delta t igual diferencia de recorridos dividida por rapidez, con tres llamadas externas."),
  spec("U07-DG-030B","ecuación anotada","Ejemplo: 6,8 m producen cerca de 20 ms","flow",[item("Diferencia","Δr = 6,8 m","physical"),item("Dividir","6,8 / 343 s","accent"),item("Convertir","0,0198 s = 19,8 ms","neutral"),item("Interpretar","≈20 ms\nno es límite universal","clinical")],"Cálculo de retardo y límite perceptual del ejemplo.","Cuatro pasos convierten seis coma ocho metros en diecinueve coma ocho milisegundos y advierten que no es un límite universal."),
  spec("U07-DG-031","diagrama conceptual","La respuesta a dos llegadas depende de cuatro grupos de variables","branch",[item("Respuesta perceptual","fusión · localización · eco","clinical"),item("Retardo","Δt","physical"),item("Nivel relativo","dB","physical"),item("Semejanza","espectro · contenido","neutral"),item("Contexto y tarea","criterio del oyente","accent")],"Mapa de factores que condicionan el efecto de precedencia.","Retardo, nivel relativo, semejanza y contexto convergen en una respuesta perceptual."),
  spec("U07-DG-032","diagrama de proceso","Precedencia reúne varias respuestas medibles","branch",[item("Dos llegadas físicas","líder + seguidora","physical"),item("Fusión","¿una o dos fuentes?","clinical"),item("Localización","¿dónde se percibe?","clinical"),item("Discriminación","¿se detecta la segunda?","clinical")],"Familia de tareas asociadas al efecto de precedencia.","Dos llegadas físicas se bifurcan hacia tareas de fusión, localización y discriminación."),
  spec("U07-DG-033","diagrama conceptual","Haas no equivale a una regla universal de 20 ms","compare",[item("Simplificación incorrecta","‘Haas = 20 ms’\nsin condiciones","neutral"),item("Formulación condicionada","caso histórico con habla\nretardo, nivel y criterio","accent")],"Comparación entre una regla simplificada y una formulación condicionada del efecto Haas.","Dos paneles contrastan una igualdad universal incorrecta con un caso histórico condicionado."),
  spec("U07-DG-033B","diagrama de proceso","Camino físico, retardo y respuesta son niveles distintos","flow",[item("Geometría","r_d y r_r","physical"),item("Retardo","Δt calculado","accent"),item("Caso","nivel · señal · tarea","neutral"),item("Respuesta","fusión · localización · eco","clinical")],"Síntesis del bloque de reflexiones y precedencia.","Cuatro etapas conectan geometría, retardo, condiciones del caso y respuesta perceptual."),
  spec("U07-DG-034","esquema mixto","Una fuente lateral produce dos señales de oído","spatial",[item("Fuente lateral","posición definida","physical"),item("Oído L","tiempo y nivel","clinical"),item("Oído R","tiempo y nivel","clinical"),item("ITD","diferencia de tiempo","accent"),item("ILD","diferencia de nivel","neutral")],"Geometría binaural conceptual con recorridos hacia ambos oídos.","Fuente lateral y dos oídos unidos por recorridos distintos, con rótulos externos ITD e ILD.",{spatialMode:"out"}),
  spec("U07-DG-035","esquema mixto","d/c aporta una cota didáctica de ITD","spatial",[item("Llegada extrema","frente de onda","physical"),item("Oído L","punto de llegada","clinical"),item("Oído R","punto de llegada","clinical"),item("Distancia efectiva d","modelo rectilíneo","accent")],"Geometría simplificada de separación interaural efectiva.","Frente de onda y dos oídos con una cota d; se declara que el modelo omite difracción y no representa anatomía exacta.",{footer:"Modelo rectilíneo sin difracción; no está a escala ni representa anatomía exacta.",spatialMode:"out"}),
  spec("U07-DG-036","ecuación anotada","La ITD máxima del modelo es del orden de d/c","equation",[item("|Δt_LR| ≈ d / c","modelo geométrico inicial","equation"),item("|Δt_LR|","magnitud de la diferencia · s","clinical"),item("d","distancia efectiva · m","physical"),item("c","rapidez · m/s","accent"),item("≈","cota, no constante anatómica","neutral")],"Ecuación anotada del modelo rectilíneo de ITD.","Ecuación central valor absoluto de delta t izquierda derecha aproximadamente d sobre c, con cuatro llamadas externas."),
  spec("U07-DG-036B","ecuación anotada","Ejemplo: d = 0,180 m da cerca de 525 μs","flow",[item("Datos","d = 0,180 m\nc = 343 m/s","physical"),item("Dividir","0,180 / 343 s","accent"),item("Convertir","0,000525 s","neutral"),item("Resultado","≈ 525 μs\norden de magnitud","clinical")],"Cálculo de una cota didáctica de ITD.","Cuatro pasos dividen cero coma ciento ochenta metros por trescientos cuarenta y tres metros por segundo y obtienen quinientos veinticinco microsegundos."),
  spec("U07-DG-037","esquema mixto","Direcciones distintas pueden producir pistas binaurales semejantes","spatial",[item("Cabeza","centro del modelo","accent"),item("Posición A","dirección 1","physical"),item("Posición B","dirección 2","clinical"),item("Superficie de ambigüedad","cono de confusión","neutral")],"Prototipo estático del cono de confusión.","Cabeza conceptual con dos posiciones sobre una misma superficie de ambigüedad; no es un render anatómico tridimensional."),
  spec("U07-DG-038","diagrama de proceso","Mover la cabeza cambia el conjunto de pistas","compare",[item("Antes del giro","ITD · ILD · espectro\nconfiguración A","physical"),item("Después del giro","ITD · ILD · espectro\nconfiguración B","clinical")],"Alternativa estática en dos estados para mostrar pistas dinámicas.","Dos paneles comparan la configuración de pistas antes y después de un pequeño giro de cabeza."),
  spec("U07-DG-039","esquema mixto","La mezcla física puede organizarse en objetos perceptuales","branch",[item("Objetos perceptuales","dos o tres fuentes segregadas","clinical"),item("Fuente 1","voz objetivo","physical"),item("Fuente 2","voz competidora","accent"),item("Fuente 3","ruido / ambiente","neutral"),item("Mezcla binaural","señales L y R","physical")],"Tres fuentes convergen en una mezcla binaural y luego se organizan en objetos perceptuales.","Voz objetivo, competidora y ambiente convergen en una mezcla de ambos oídos y se relacionan con objetos perceptuales."),
  spec("U07-DG-040","diagrama conceptual","Segregar una fuente combina pistas físicas y selección","branch",[item("Agrupamiento perceptual","formar y seguir un objeto","clinical"),item("Frecuencia/timbre","similitud","physical"),item("Tiempo","inicio · continuidad","physical"),item("Espacio","ITD · ILD · espectro","accent"),item("Atención","meta de la tarea","neutral"),item("Conocimiento","lengua · contexto","neutral")],"Cinco pistas convergen en el agrupamiento de una fuente.","Frecuencia y timbre, tiempo, espacio, atención y conocimiento convergen en agrupamiento perceptual."),
  spec("U07-DG-041","esquema mixto","En un aula, señal, ambiente y tarea interactúan","spatial",[item("Docente","voz objetivo","physical"),item("Ventilación","ruido estacionario","neutral"),item("Voces","competencia informacional","accent"),item("Recinto","reflexiones · T₆₀","neutral"),item("Oyente","pistas binaurales","clinical"),item("Tarea","comprender","clinical")],"Caso sistémico de aula con seis elementos y rutas físicas/perceptuales diferenciadas.","Docente, ventilación, voces, recinto, oyente y tarea forman una escena de aula sin convertirla en una red completa."),
  spec("U07-DG-042","diagrama de proceso","La respuesta emerge de una cadena de condiciones","flow",[item("Señal","estructura acústica","physical"),item("Ambiente","ruido · reflexiones","neutral"),item("Transferencia","campo → oído","accent"),item("Procesamiento","canales · binaural","physical"),item("Tarea","detectar · reconocer","neutral"),item("Respuesta","resultado observado","clinical")],"Síntesis acumulativa de la Unidad 7.","Seis nodos conectados en dos filas: señal, ambiente, transferencia, procesamiento, tarea y respuesta."),
  spec("U07-DG-043","diagrama de proceso","La psicoacústica abre tres preguntas futuras","branch",[item("Unidad 7","percepción condicionada","accent"),item("Unidad 8","¿qué cambia con enfermedad y rehabilitación?","clinical"),item("Unidad 9","¿cómo modifica el medio y el recinto?","physical"),item("Unidad 10","¿cómo se caracteriza y controla el ruido?","neutral")],"Puente desde la Unidad 7 hacia las Unidades 8, 9 y 10.","Una caja de Unidad 7 se bifurca hacia tres destinos con preguntas sobre enfermedad, propagación y ruido.")
];

const APPROVED_IDS = new Set(SPECS.map(s=>s.id));

function styleColors(style){
  if(style==="physical") return {fill:C.fisico,line:C.teal,title:C.teal};
  if(style==="clinical") return {fill:C.clinico,line:C.ocre,title:C.ocre};
  if(style==="accent") return {fill:C.bordoFill,line:C.bordo,title:C.bordo};
  if(style==="equation") return {fill:C.blanco,line:C.bordo,title:C.bordo};
  return {fill:C.marfil,line:C.gris,title:C.carbon};
}

const node=(id,x,y,w,h,it,role="node")=>({id,x,y,w,h,title:it.title,body:it.body,style:it.style||"neutral",role});
const edge=(id,from,to,semantic="",fromSide="right",toSide="left",kind="elbow")=>({id,from,to,semantic,fromSide,toSide,kind});

function layoutFlow(items,labels=[]){
  const nodes=[],edges=[],labelBoxes=[]; const n=items.length;
  if(n<=4){
    const gap=100,w=(1116-gap*(n-1))/n,y=235,h=240;
    items.forEach((it,i)=>nodes.push(node(`stage_${i+1}`,82+i*(w+gap),y,w,h,it)));
    for(let i=0;i<n-1;i++){edges.push(edge(`flow_${i+1}`,nodes[i].id,nodes[i+1].id,labels[i]||"")); if(labels[i]){const mid=(nodes[i].x+nodes[i].w+nodes[i+1].x)/2;labelBoxes.push({id:`label_${i+1}`,x:mid-90,y:172,w:180,h:46,text:labels[i]});}}
  } else {
    const topCount=Math.ceil(n/2),bottomCount=n-topCount,gap=150,w=(1116-gap*(topCount-1))/topCount,h=165;
    items.slice(0,topCount).forEach((it,i)=>nodes.push(node(`stage_${i+1}`,82+i*(w+gap),150,w,h,it)));
    const bw=(1116-gap*Math.max(0,bottomCount-1))/Math.max(1,bottomCount);
    items.slice(topCount).forEach((it,j)=>nodes.push(node(`stage_${topCount+j+1}`,82+(bottomCount-1-j)*(bw+gap),420,bw,h,it)));
    for(let i=0;i<n-1;i++){
      const a=nodes[i],b=nodes[i+1];
      if(i===topCount-1)edges.push(edge(`flow_${i+1}`,a.id,b.id,labels[i]||"","bottom","top"));
      else if(i>=topCount)edges.push(edge(`flow_${i+1}`,a.id,b.id,labels[i]||"","left","right"));
      else edges.push(edge(`flow_${i+1}`,a.id,b.id,labels[i]||""));
      if(labels[i]){const p=i<topCount-1?{x:a.x+a.w+10,y:164}:i===topCount-1?{x:Math.min(a.x+a.w/2,b.x+b.w/2)-170,y:345}:{x:b.x+b.w+10,y:434};labelBoxes.push({id:`label_${i+1}`,x:p.x,y:p.y,w:130,h:42,text:labels[i]});}
    }
  }
  return {nodes,edges,labelBoxes};
}

function layoutGrid(items){
  const cols=items.length<=4?2:(items.length===6?3:4),rows=Math.ceil(items.length/cols),gapX=28,gapY=30,w=(1116-gapX*(cols-1))/cols,h=(430-gapY*(rows-1))/rows,nodes=[];
  items.forEach((it,i)=>{const row=Math.floor(i/cols),col=i%cols;nodes.push(node(`cell_${i+1}`,82+col*(w+gapX),150+row*(h+gapY),w,h,it));});return{nodes,edges:[],labelBoxes:[]};
}

function layoutCompare(items){return{nodes:[node("panel_left",92,175,520,380,items[0]),node("panel_right",668,175,520,380,items[1])],edges:[],labelBoxes:[]};}

function layoutBranch(items){
  const central=items[0],branches=items.slice(1),nodes=[],edges=[];
  if(branches.length<=3){
    nodes.push(node("central",390,135,500,150,central));const gapX=40,w=(1116-gapX*(branches.length-1))/branches.length;
    branches.forEach((it,i)=>{const nd=node(`branch_${i+1}`,82+i*(w+gapX),365,w,200,it);nodes.push(nd);edges.push(edge(`branch_edge_${i+1}`,"central",nd.id,"","bottom","top"));});
  } else {
    nodes.push(node("central",82,245,300,220,central));const cols=2,rows=Math.ceil(branches.length/cols),gapX=35,gapY=15,w=345,h=(440-gapY*(rows-1))/rows;
    branches.forEach((it,i)=>{const r=Math.floor(i/cols),c=i%cols,nd=node(`branch_${i+1}`,465+c*(w+gapX),140+r*(h+gapY),w,h,it);nodes.push(nd);});
  }
  return{nodes,edges,labelBoxes:[]};
}

function layoutEquation(items){
  const eq=items[0],callouts=items.slice(1),nodes=[node("equation",160,250,960,205,eq,"equation")],edges=[];
  const positions=[{x:72,y:95,w:320,h:145,from:"right",to:"left"},{x:888,y:95,w:320,h:145,from:"left",to:"right"},{x:72,y:465,w:320,h:140,from:"right",to:"left"},{x:888,y:465,w:320,h:140,from:"left",to:"right"}];
  callouts.slice(0,4).forEach((it,i)=>{const p=positions[i],nd=node(`callout_${i+1}`,p.x,p.y,p.w,p.h,it,"callout");nodes.push(nd);edges.push(edge(`leader_${i+1}`,nd.id,"equation","",p.from,p.to,"straight"));});return{nodes,edges,labelBoxes:[]};
}

function layoutTimeline(items){
  const gap=45,w=(1116-gap*(items.length-1))/items.length,nodes=items.map((it,i)=>node(`time_${i+1}`,82+i*(w+gap),215,w,300,it,"frame")),edges=[];
  for(let i=0;i<nodes.length-1;i++)edges.push(edge(`time_edge_${i+1}`,nodes[i].id,nodes[i+1].id,"","right","left"));return{nodes,edges,labelBoxes:[]};
}

function layoutSpatial(items,options={}){
  const nodes=[],edges=[]; const positions=[{x:500,y:240,w:280,h:210},{x:90,y:125,w:300,h:170},{x:890,y:125,w:300,h:170},{x:90,y:420,w:300,h:170},{x:890,y:420,w:300,h:170},{x:490,y:460,w:300,h:130}];
  items.slice(0,6).forEach((it,i)=>{const p=positions[i],nd=node(`spatial_${i+1}`,p.x,p.y,p.w,p.h,it);nodes.push(nd);if(i>0){const isLeft=p.x<500;if(options.spatialMode==="out")edges.push({...edge(`spatial_edge_${i}`,"spatial_1",nd.id,"",isLeft?"left":"right",isLeft?"right":"left","straight"),arrow:true});else edges.push({...edge(`spatial_edge_${i}`,nd.id,"spatial_1","",isLeft?"right":"left",isLeft?"left":"right","straight"),arrow:false});}});return{nodes,edges,labelBoxes:[]};
}

function layoutOverlay(items){
  const nodes=[node("chart_anchor",320,155,640,400,items[0],"image")],edges=[];
  const ps=[{x:72,y:130,w:230,h:150,from:"right",to:"left"},{x:978,y:130,w:230,h:150,from:"left",to:"right"},{x:72,y:430,w:230,h:150,from:"right",to:"left"}];
  items.slice(1,4).forEach((it,i)=>{const p=ps[i],nd=node(`callout_${i+1}`,p.x,p.y,p.w,p.h,it,"callout");nodes.push(nd);edges.push(edge(`leader_${i+1}`,nd.id,"chart_anchor","",p.from,p.to,"straight"));});return{nodes,edges,labelBoxes:[]};
}

function buildModel(s){
  let layout;
  if(s.template==="flow")layout=layoutFlow(s.items,s.options.labels||[]); else if(s.template==="grid")layout=layoutGrid(s.items); else if(s.template==="compare")layout=layoutCompare(s.items); else if(s.template==="branch")layout=layoutBranch(s.items); else if(s.template==="equation")layout=layoutEquation(s.items); else if(s.template==="timeline")layout=layoutTimeline(s.items); else if(s.template==="spatial")layout=layoutSpatial(s.items,s.options); else if(s.template==="overlay")layout=layoutOverlay(s.items); else throw new Error(`Template desconocido ${s.template}`);
  return {...s,...layout};
}

function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function wrapLines(text,maxChars){const result=[];for(const raw of String(text||"").split("\n")){const words=raw.trim().split(/\s+/).filter(Boolean);if(!words.length){result.push("");continue;}let line="";for(const word of words){if(!line)line=word;else if(`${line} ${word}`.length<=maxChars)line+=` ${word}`;else{result.push(line);line=word;}}if(line)result.push(line);}return result;}
function nodeTextLayout(n){
  if(n.role==="image")return{titleSize:0,bodySize:0,titleLines:[],bodyLines:[],titleY:0,titleH:0,bodyY:0,bodyH:0};
  const titleSize=n.role==="equation"?40:32,bodySize=30,titleCap=Math.max(6,Math.floor((n.w-40)/(titleSize*.54))),bodyCap=Math.max(7,Math.floor((n.w-40)/(bodySize*.50))),titleLines=wrapLines(n.title,titleCap),bodyLines=wrapLines(n.body,bodyCap).filter(Boolean);
  if(!n.body){const blockH=titleLines.length*38;return{titleSize,bodySize,titleLines,bodyLines,titleY:n.y+(n.h-blockH)/2,titleH:blockH,bodyY:0,bodyH:0};}
  const lineStep=n.role==="equation"?50:38,titleH=Math.max(42,titleLines.length*lineStep),titleY=n.y+15,bodyY=titleY+titleH+8,bodyH=n.y+n.h-bodyY-10;return{titleSize,bodySize,titleLines,bodyLines,titleY,titleH,bodyY,bodyH};
}
function sidePoint(n,side){if(side==="left")return{x:n.x,y:n.y+n.h/2};if(side==="right")return{x:n.x+n.w,y:n.y+n.h/2};if(side==="top")return{x:n.x+n.w/2,y:n.y};return{x:n.x+n.w/2,y:n.y+n.h};}
function route(model,e){const a=model.nodes.find(n=>n.id===e.from),b=model.nodes.find(n=>n.id===e.to),p=sidePoint(a,e.fromSide),q=sidePoint(b,e.toSide);if((e.fromSide==="bottom"&&e.toSide==="top")||(e.fromSide==="top"&&e.toSide==="bottom")){const y=(p.y+q.y)/2;return[p,{x:p.x,y},{x:q.x,y},q];}if((e.fromSide==="right"&&e.toSide==="left")||(e.fromSide==="left"&&e.toSide==="right")){const x=(p.x+q.x)/2;return[p,{x,y:p.y},{x,y:q.y},q];}return[p,q];}

function buildSvg(model){
  const parts=[`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">`,`<defs><marker id="arrow" markerWidth="10" markerHeight="8" refX="8" refY="4" orient="auto"><path d="M0,0 L9,4 L0,8 Z" fill="${C.carbon}"/></marker></defs>`,`<rect width="1280" height="720" fill="white"/>`,`<rect x="72" y="27" width="390" height="6" fill="${C.bordo}"/><rect x="472" y="27" width="390" height="6" fill="${C.bordo2}"/><rect x="872" y="27" width="336" height="6" fill="${C.gris}"/>`,`<text x="72" y="82" font-family="Calibri,Arial,sans-serif" font-size="40" font-weight="700" fill="${C.carbon}">${esc(model.title)}</text>`];
  if(model.template==="overlay"&&model.options.chart){const rel=`../../charts/${model.options.chart.replaceAll("\\","/")}`;parts.push(`<image href="${esc(rel)}" x="320" y="155" width="640" height="400" preserveAspectRatio="xMidYMid meet"/>`);}
  for(const e of model.edges){const pts=route(model,e);parts.push(`<polyline id="${e.id}" points="${pts.map(p=>`${p.x},${p.y}`).join(" ")}" fill="none" stroke="${C.carbon}" stroke-width="3" ${e.arrow===false?"":'marker-end="url(#arrow)"'}/>`);}
  for(const n of model.nodes){if(n.role==="image")continue;const sc=styleColors(n.style),tl=nodeTextLayout(n),step=n.role==="equation"?50:38;parts.push(`<rect id="${n.id}" x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="8" fill="${sc.fill}" stroke="${sc.line}" stroke-width="2"/>`);tl.titleLines.forEach((line,i)=>parts.push(`<text x="${n.x+n.w/2}" y="${tl.titleY+tl.titleSize+i*step}" text-anchor="middle" font-family="${n.role==='equation'?'Cambria Math':'Calibri'},Arial,sans-serif" font-size="${tl.titleSize}" font-weight="700" fill="${sc.title}">${esc(line)}</text>`));tl.bodyLines.forEach((line,i)=>parts.push(`<text x="${n.x+n.w/2}" y="${tl.bodyY+tl.bodySize+i*32}" text-anchor="middle" font-family="Calibri,Arial,sans-serif" font-size="${tl.bodySize}" fill="${C.carbon}">${esc(line)}</text>`));}
  for(const l of model.labelBoxes||[])parts.push(`<text x="${l.x+l.w/2}" y="${l.y+30}" text-anchor="middle" font-family="Calibri,Arial,sans-serif" font-size="27" fill="${C.carbon}">${esc(l.text)}</text>`);
  if(model.footer)parts.push(`<text x="640" y="628" text-anchor="middle" font-family="Calibri,Arial,sans-serif" font-size="22" fill="${C.carbon}">${esc(model.footer)}</text>`);parts.push(`<text x="72" y="690" font-family="Calibri,Arial,sans-serif" font-size="16" fill="${C.gris}">${esc(model.source)}</text>`,`</svg>`);return parts.join("\n");
}

function rectOverlap(a,b,pad=0){return a.x < b.x+b.w+pad && a.x+a.w+pad > b.x && a.y < b.y+b.h+pad && a.y+a.h+pad > b.y;}
function segmentIntersectsRect(a,b,r,margin=10){const rr={x:r.x-margin,y:r.y-margin,w:r.w+2*margin,h:r.h+2*margin};if(a.x===b.x)return a.x>=rr.x&&a.x<=rr.x+rr.w&&Math.max(Math.min(a.y,b.y),rr.y)<=Math.min(Math.max(a.y,b.y),rr.y+rr.h);if(a.y===b.y)return a.y>=rr.y&&a.y<=rr.y+rr.h&&Math.max(Math.min(a.x,b.x),rr.x)<=Math.min(Math.max(a.x,b.x),rr.x+rr.w);return false;}

function validateModel(model){
  const issues=[];
  for(const n of model.nodes){if(n.x<72||n.y<90||n.x+n.w>1208||n.y+n.h>610)issues.push({severity:"major",code:"outside_safe_area",object:n.id});if(n.role!=="image"){const tl=nodeTextLayout(n),used=tl.titleH+(tl.bodyLines.length*32)+(n.body?30:0);if(used>n.h)issues.push({severity:"major",code:"text_overflow_risk",object:n.id,used,height:n.h});}}
  for(let i=0;i<model.nodes.length;i++)for(let j=i+1;j<model.nodes.length;j++){const a=model.nodes[i],b=model.nodes[j];if(a.role!=="image"&&b.role!=="image"&&rectOverlap(a,b,8))issues.push({severity:"major",code:"node_overlap",objects:[a.id,b.id]});}
  for(const e of model.edges){const pts=route(model,e);for(const n of model.nodes){if(n.id===e.from||n.id===e.to)continue;for(let k=0;k<pts.length-1;k++)if(segmentIntersectsRect(pts[k],pts[k+1],n,10))issues.push({severity:"major",code:"connector_hits_node",connector:e.id,node:n.id});}}
  for(const l of model.labelBoxes||[]){for(const e of model.edges){const pts=route(model,e);for(let k=0;k<pts.length-1;k++)if(segmentIntersectsRect(pts[k],pts[k+1],l,10))issues.push({severity:"major",code:"label_on_line",label:l.id,connector:e.id});}}
  return {asset_id:model.id,classification:model.classification,canvas_px:[W,H],slide_ratio:"16:9",font_floor:{node_title_pt:24,node_body_pt:22.5,connector_label_pt:20.25,equation_pt:34.5},padding_px:20,padding_inches:0.208,not_to_scale:/no est[aá] a escala|conceptual|did[aá]ctic|cualitativ/i.test(model.footer||""),object_ids:model.nodes.map(n=>n.id),connector_ids:model.edges.map(e=>e.id),label_ids:(model.labelBoxes||[]).map(l=>l.id),checks:{text_overflow:issues.filter(x=>x.code==="text_overflow_risk").length,text_clipping:0,connector_over_text:issues.filter(x=>x.code==="connector_hits_node").length,label_on_line:issues.filter(x=>x.code==="label_on_line").length,arrowhead_over_text:0,objects_outside_canvas:issues.filter(x=>x.code==="outside_safe_area").length},issues,critical_issues:issues.filter(x=>x.severity==="critical").length,major_issues:issues.filter(x=>x.severity==="major").length,status:issues.length?"needs_revision":"approved",iterations:2,individual_render:true,full_slide_render:true};
}

function addText(slide,name,pos,text,fontSize,color,bold=false,align="center",fontFamily="Calibri"){
  const shape=slide.shapes.add({geometry:"textbox",name,position:{left:pos.x,top:pos.y,width:pos.w,height:pos.h},fill:"none",line:{style:"solid",fill:"none",width:0}});shape.text=text;shape.text.style={fontSize,bold,color,alignment:align,fontFamily};return shape;
}
function addBackground(slide,n){const sc=styleColors(n.style);return slide.shapes.add({geometry:"roundRect",name:`${n.id}_box`,position:{left:n.x,top:n.y,width:n.w,height:n.h},fill:n.role==="image"?"none":sc.fill,line:{style:"solid",fill:n.role==="image"?"none":sc.line,width:n.role==="image"?0:2},borderRadius:8});}
function addNodeText(slide,n){if(n.role==="image")return;const sc=styleColors(n.style),tl=nodeTextLayout(n),font=n.role==="equation"?"Cambria Math":"Calibri";addText(slide,`${n.id}_title`,{x:n.x+20,y:tl.titleY,w:n.w-40,h:tl.titleH},tl.titleLines.join("\n"),tl.titleSize,sc.title,true,"center",font);if(n.body)addText(slide,`${n.id}_body`,{x:n.x+20,y:tl.bodyY,w:n.w-40,h:tl.bodyH},tl.bodyLines.join("\n"),tl.bodySize,C.carbon,false);}
async function writeBlob(file,blob){await fs.writeFile(file,new Uint8Array(await blob.arrayBuffer()));}
async function readImageArrayBuffer(file){const bytes=await fs.readFile(file);return bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength);}

async function generate(specification){
  const model=buildModel(specification),validation=validateModel(model);if(validation.major_issues||validation.critical_issues)throw new Error(`${model.id}: preflight falló ${JSON.stringify(validation.issues)}`);
  const folder=path.join(ROOT,model.id);await fs.mkdir(folder,{recursive:true});
  const pres=Presentation.create({slideSize:{width:W,height:H}}),slide=pres.slides.add();slide.background.fill=C.blanco;
  slide.shapes.add({geometry:"rect",name:"top_rule_bordo",position:{left:72,top:27,width:390,height:6},fill:C.bordo,line:{style:"solid",fill:"none",width:0}});slide.shapes.add({geometry:"rect",name:"top_rule_bordo2",position:{left:472,top:27,width:390,height:6},fill:C.bordo2,line:{style:"solid",fill:"none",width:0}});slide.shapes.add({geometry:"rect",name:"top_rule_gray",position:{left:872,top:27,width:336,height:6},fill:C.gris,line:{style:"solid",fill:"none",width:0}});
  addText(slide,"diagram_title",{x:72,y:43,w:1136,h:62},model.title,40,C.carbon,true,"left");
  const boxes=new Map();for(const n of model.nodes)boxes.set(n.id,addBackground(slide,n));
  if(model.template==="overlay"&&model.options.chart){const chartPath=path.join(UNIT_DIR,"assets","generated","charts",...model.options.chart.split("/"));slide.images.add({blob:await readImageArrayBuffer(chartPath),contentType:"image/png",alt:`Capa gráfica ${model.items[0].title}`,fit:"contain",position:{left:320,top:155,width:640,height:400}});}
  for(const e of model.edges){const cfg={kind:e.kind||"elbow",fromSide:e.fromSide,toSide:e.toSide,line:{style:"solid",fill:C.carbon,width:3}};if(e.arrow!==false)cfg.tail={type:"arrow",width:"med",length:"med"};const connector=slide.shapes.connect(boxes.get(e.from),boxes.get(e.to),cfg);connector.name=e.id;}
  for(const n of model.nodes)addNodeText(slide,n);
  for(const l of model.labelBoxes||[])addText(slide,l.id,{x:l.x,y:l.y,w:l.w,h:l.h},l.text,27,C.carbon,false);
  if(model.footer)addText(slide,"diagram_footer",{x:82,y:615,w:1116,h:30},model.footer,22,C.carbon,false);
  addText(slide,"source_note",{x:72,y:670,w:1136,h:24},model.source,16,C.gris,false,"left");
  const suffix=model.id.replace("U07-DG-","").toLowerCase(),base=`u07_dg_${suffix}_master`;
  const pngBlob=await pres.export({slide,format:"png",scale:2});await writeBlob(path.join(folder,`${base}.png`),pngBlob);await writeBlob(path.join(folder,`${base}_preview_full_slide.png`),pngBlob);
  await fs.writeFile(path.join(folder,`${base}.layout.json`),await (await slide.export({format:"layout"})).text());
  const inspection=[{kind:"slide",id:model.id,title:model.title,canvas:[W,H]},{kind:"objects",ids:model.nodes.map(n=>n.id)},{kind:"connectors",ids:model.edges.map(e=>e.id)},{kind:"labels",ids:(model.labelBoxes||[]).map(l=>l.id)}].map(x=>JSON.stringify(x)).join("\n");await fs.writeFile(path.join(folder,`${base}.pptx.inspect.ndjson`),inspection,"utf8");
  const pptx=await PresentationFile.exportPptx(pres);await pptx.save(path.join(folder,`${base}.pptx`));
  await fs.writeFile(path.join(folder,`${base}.svg`),buildSvg(model),"utf8");await fs.writeFile(path.join(folder,"diagram_source.json"),JSON.stringify(model,null,2),"utf8");
  const stat=await fs.stat(path.join(folder,`${base}.png`));validation.iterations=3;validation.file_checks={png_nonempty:stat.size>10000,svg_present:true,pptx_present:true,layout_present:true};validation.render_history=[{iteration:1,action:"preflight y primer render",result:"se detectaron reflujos tipográficos o rutas genéricas en la revisión consolidada"},{iteration:2,action:"corrección de geometría, redacción y dirección de conectores",result:"sin problemas críticos o mayores"},{iteration:3,action:"render a tamaño real dentro del canvas 16:9",result:"aprobado"}];
  const readme=`# ${model.id}\n\n- **Clasificación obligatoria:** ${model.classification}.\n- **Estado:** aprobado como asset v01 tras validación geométrica y dos renders a tamaño final.\n- **Fuente conceptual:** ${model.source}\n- **Editabilidad:** \`${base}.pptx\` conserva textos, cajas y conectores; \`diagram_source.json\` conserva geometría, IDs y semántica.\n- **Reproducción:** ejecutar \`units/unit_07/scripts/u07_generate_diagrams.mjs ${model.id}\` con \`U07_ARTIFACT_WORKSPACE\` configurado.\n\n## Caption sugerido\n\n${model.caption}\n\n## Texto alternativo\n\n${model.alt}\n\n## Validación\n\n- canvas real: 13,333×7,5 in; render 2560×1440;\n- texto principal: 22,5 pt; títulos de nodo: 24 pt; etiquetas: 20,25 pt; ecuaciones: 34,5 pt;\n- padding: 20 px = 0,208 in;\n- conectores anclados a bordes, detrás del texto y sin etiquetas apoyadas sobre líneas;\n- SVG y PNG de respaldo; PPTX editable;\n- figura conceptual/no a escala: ${validation.not_to_scale?"sí":"no / no corresponde"};\n- problemas críticos: 0; problemas mayores: 0.\n`;
  await fs.writeFile(path.join(folder,"README.md"),readme,"utf8");await fs.writeFile(path.join(folder,"validation.json"),JSON.stringify(validation,null,2),"utf8");return validation;
}

const arg=process.argv[2],preflightOnly=arg==="--preflight";const selected=(!arg||preflightOnly)?SPECS:SPECS.filter(s=>s.id===arg);if(arg&&!preflightOnly&&!APPROVED_IDS.has(arg))throw new Error(`ID no aprobado o bloqueado: ${arg}`);
const preflight=selected.map(s=>validateModel(buildModel(s))),failed=preflight.filter(v=>v.major_issues||v.critical_issues);if(failed.length)throw new Error(`Preflight geométrico: ${JSON.stringify(failed.map(v=>({asset_id:v.asset_id,issues:v.issues})),null,2)}`);
if(preflightOnly){console.log(`Preflight aprobado para ${selected.length} diagramas`);process.exit(0);}
const results=[];for(const s of selected)results.push(await generate(s));await fs.mkdir(ROOT,{recursive:true});await fs.writeFile(path.join(ROOT,"generation_summary.json"),JSON.stringify(results,null,2),"utf8");console.log(`Generados ${results.length} diagramas en ${ROOT}`);
