/** Genera masters editables y previews validados de los diagramas U05 aprobados. */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const UNIT_DIR = path.dirname(SCRIPT_DIR);
const ROOT = path.join(UNIT_DIR, "assets", "generated", "diagrams");
const artifactWorkspace = process.env.U05_ARTIFACT_WORKSPACE;
if (!artifactWorkspace) throw new Error("Definir U05_ARTIFACT_WORKSPACE con un workspace inicializado para @oai/artifact-tool");
const workspaceRequire = createRequire(path.join(path.resolve(artifactWorkspace), "package.json"));
const artifactEntry = workspaceRequire.resolve("@oai/artifact-tool");
const { Presentation, PresentationFile } = await import(pathToFileURL(artifactEntry).href);

const C = { bordo:"#4D1434", bordo2:"#903163", teal:"#2F7E83", carbon:"#3D3D3D", gris:"#969FA7", gris2:"#D9DCE0", marfil:"#F7F6F2", fisico:"#E7F1F1", ocre:"#9F541A", clinico:"#F8EDE2", blanco:"#FFFFFF", error:"#A33A3A", ok:"#2F6F55" };
const W=1280, H=720, SAFE={left:72,top:96,right:1208,bottom:652};

const n=(id,x,y,w,h,title,body="",style="neutral",role="node")=>({id,x,y,w,h,title,body,style,role});
const e=(id,from,to,semantic="",fromSide="right",toSide="left")=>({id,from,to,label:"",semantic,fromSide,toSide});

const MODELS = {
  "U05-DG-001": {classification:"diagrama conceptual", title:"De la señal a una medición interpretable", source:"Programa oficial, brief y storyboard U05; mapa narrativo propio.", caption:"Mapa de cuatro etapas que organiza la unidad desde la señal registrada hasta la medición informada.", alt:"Cuatro bloques horizontales conectados: señal, representación, interpretación y medición. Cada bloque enumera dos ideas de la etapa.", nodes:[
    n("stage_signal",80,250,245,150,"1 · Señal","tiempo · RMS","physical"), n("stage_repr",370,250,245,150,"2 · Fourier","serie · DFT","accent"), n("stage_interpret",660,250,245,150,"3 · Lectura","sistemas · bandas","neutral"), n("stage_measure",950,250,245,150,"4 · Medición","ponderación\nsonómetro","clinical")], edges:[e("edge_1", "stage_signal","stage_repr","describe"),e("edge_2","stage_repr","stage_interpret","permite leer"),e("edge_3","stage_interpret","stage_measure","sustenta")]},
  "U05-DG-002": {classification:"diagrama de proceso", title:"Rutina para leer cualquier representación", source:"Storyboard U05 y decisiones pedagógicas del proyecto.", caption:"Secuencia estable de cinco preguntas: objeto, ejes, unidades, condiciones e interpretación.", alt:"Cinco cajas numeradas forman un flujo en dos filas. La rutina comienza por identificar el objeto y termina por formular una interpretación limitada por las condiciones.", nodes:[
    n("read_object",90,155,300,130,"1 · Objeto","¿señal o sistema?","physical"),n("read_axes",490,155,300,130,"2 · Ejes","t o f","neutral"),n("read_units",890,155,300,130,"3 · Unidades","s · Hz · Pa · dB","neutral"),n("read_conditions",890,390,300,130,"4 · Condiciones","ventana · ref.","accent"),n("read_meaning",490,390,300,130,"5 · Interpretar","alcance","clinical")], edges:[e("read_1","read_object","read_axes"),e("read_2","read_axes","read_units"),e("read_3","read_units","read_conditions","","bottom","top"),e("read_4","read_conditions","read_meaning","","left","right")]},
  "U05-DG-003": {classification:"ecuación anotada", title:"Magnitud y fase describen partes distintas de X(f)", source:"Libro del curso, ecuaciones 5.5 y 5.6; convención de transformada declarada.", caption:"Ecuación polar de la transformada con callouts separados para cantidad compleja, magnitud, fase y frecuencia.", alt:"La expresión X de f igual a módulo de X por exponencial de j phi aparece al centro. Cuatro cajas externas explican la cantidad compleja, la magnitud, la fase en radianes y la frecuencia en hertz.", nodes:[
    n("eq_x",250,280,165,105,"X(f)","","equation"),n("eq_equal",430,280,60,105,"=","","equation"),n("eq_mag",505,280,210,105,"|X(f)|","","equation"),n("eq_phase",745,280,245,105,"eʲφˣ⁽ᶠ⁾","","equation"),
    n("callout_quantity",90,135,245,105,"Transformada","unidad U·s","neutral"),n("callout_magnitude",410,455,260,105,"Magnitud","escala declarada","physical"),n("callout_phase",760,455,250,105,"Fase relativa","φₓ(f) en rad","clinical"),n("callout_frequency",1005,135,200,105,"Variable","f en Hz","accent")],
    edges:[e("lead_quantity","callout_quantity","eq_x","","right","left"),e("lead_magnitude","callout_magnitude","eq_mag","","top","bottom"),e("lead_phase","callout_phase","eq_phase","","top","bottom"),e("lead_frequency","callout_frequency","eq_phase","","left","right")]},
  "U05-DG-004": {classification:"diagrama de proceso", title:"La cadena digital fija qué frecuencias podemos observar", source:"Libro del curso, secciones 5.4.4 y 5.4.5.", caption:"Cadena de captura, muestreo, segmentación, ventana, DFT y bins con parámetros visibles.", alt:"Seis bloques conectados de izquierda a derecha muestran captura, muestras, segmento, ventana, DFT y bins. Debajo se declaran frecuencia de muestreo, cantidad de muestras, duración y separación entre bins.", nodes:[
    n("capture",90,155,300,130,"1 · Captura","p(t)","physical"),n("samples",490,155,300,130,"2 · Muestras","fₛ en Hz","physical"),n("segment",890,155,300,130,"3 · Segmento","N muestras","neutral"),n("window",890,390,300,130,"4 · Ventana","recorte declarado","accent"),n("dft",490,390,300,130,"5 · DFT","FFT = algoritmo","neutral"),n("bins",90,390,300,130,"6 · Bins","Δf en Hz","clinical")], edges:[e("dig_1","capture","samples"),e("dig_2","samples","segment"),e("dig_3","segment","window","","bottom","top"),e("dig_4","window","dft","","left","right"),e("dig_5","dft","bins","","left","right")], footer:"T_obs = N/fₛ      ·      Δf = fₛ/N = 1/T_obs"},
  "U05-DG-005": {classification:"esquema mixto", title:"Recortar y agrupar son operaciones distintas", source:"Libro del curso, ventanas, espectrograma y suma por banda.", caption:"Proceso conceptual desde una señal larga hasta segmentos, espectros locales, espectrograma y agrupación en bandas.", alt:"Cinco bloques conectados muestran señal larga, selección de segmento, aplicación de ventana, espectros por tiempo y agrupación de bins en bandas.", nodes:[
    n("long_signal",85,240,190,145,"Señal","registro","physical"),n("selection",315,240,190,145,"Tramo","selección","neutral"),n("multiply_window",545,240,190,145,"Ventana","multiplica","accent"),n("local_spectra",775,240,190,145,"Espectros","rejilla t–f","physical"),n("group_bands",1005,240,190,145,"Bandas","suma energía","clinical")], edges:[e("mix_1","long_signal","selection","recorta"),e("mix_2","selection","multiply_window","pondera"),e("mix_3","multiply_window","local_spectra","DFT"),e("mix_4","local_spectra","group_bands","suma energía")], footer:"Figura conceptual; no está a escala."},
  "U05-DG-006": {classification:"diagrama conceptual", title:"El espectro pertenece a la señal; H(f) pertenece al sistema", source:"Libro del curso, ecuaciones H(f)=Y(f)/X(f) y G(f)=20 log10|H(f)|.", caption:"Cadena entrada–sistema–salida que distingue espectros de señales y respuesta del sistema.", alt:"Tres bloques grandes conectados muestran entrada X de f, sistema H de f y salida Y de f. Debajo aparecen las relaciones Y igual X por H, H igual Y sobre X cuando X no es cero y ganancia en decibeles.", nodes:[
    n("input_x",120,220,260,165,"Entrada X(f)","espectro de una señal","physical"),n("system_h",510,220,260,165,"Sistema H(f)","respuesta\nfrecuencial","accent"),n("output_y",900,220,260,165,"Salida Y(f)","espectro de otra señal","physical")], edges:[e("sys_1","input_x","system_h","atraviesa"),e("sys_2","system_h","output_y","modifica")], footer:"Y(f)=X(f)H(f)      ·      H(f)=Y(f)/X(f), X(f)≠0      ·      G(f)=20 log₁₀|H(f)|"},
  "U05-DG-007": {classification:"esquema mixto", title:"Los nombres espectrales no describen la misma relación", source:"Libro del curso, secciones 5.5 y 5.6; aplicación fuente–filtro de voz.", caption:"Taxonomía breve de componentes y cadena fuente–filtro que separa armónicos de formantes.", alt:"La zona superior relaciona frecuencia fundamental, armónico, parcial y sobretono. La zona inferior muestra una fuente periódica, el tracto vocal como filtro y una salida con líneas armónicas bajo una envolvente.", nodes:[
    n("fundamental",80,145,250,115,"Fundamental","f₀ = 1/T₀","physical"),n("harmonic",365,145,250,115,"Armónico","fₙ = n f₀","accent"),n("partial",650,145,250,115,"Parcial","armónico o no","neutral"),n("overtone",935,145,250,115,"Sobretono","parcial sobre f₀","clinical"),
    n("voice_source",175,420,250,120,"Fuente","armónicos","physical"),n("vocal_filter",515,420,250,120,"Tracto vocal","formantes","accent"),n("voice_output",855,420,250,120,"Salida","señal filtrada","clinical")], edges:[e("tax_1","fundamental","harmonic","genera múltiplos"),e("tax_2","harmonic","partial","es un caso de"),e("tax_3","partial","overtone","si está sobre f₀"),e("voice_1","voice_source","vocal_filter","atraviesa"),e("voice_2","vocal_filter","voice_output","modela")], footer:"Formante ≠ armónico · figura conceptual; no está a escala."},
  "U05-DG-008": {classification:"esquema mixto", title:"Un rango sólo tiene sentido si sus límites están condicionados", source:"Libro del curso, sección 5.7.", caption:"Comparación de región frecuencial y rango dinámico con condiciones explícitas.", alt:"Dos bandas grandes muestran regiones de frecuencia y un rango dinámico entre límite inferior y superior. Cuatro cajas inferiores exigen declarar persona o fuente, estímulo, nivel y método de medición.", nodes:[
    n("frequency_range",95,155,500,140,"Región de frecuencia","infra · audible · ultra","physical"),n("dynamic_range",685,155,500,140,"Rango dinámico","R_D = L_sup − L_inf","clinical"),
    n("condition_source",95,400,240,145,"Origen","persona / fuente","neutral"),n("condition_stimulus",375,400,240,145,"Estímulo","f · duración","neutral"),n("condition_level",655,400,240,145,"Descriptor","RMS · pico\nL_eq","neutral"),n("condition_method",935,400,250,145,"Medición","distancia · X","accent")], edges:[e("cond_1","frequency_range","condition_stimulus","depende de","bottom","top"),e("cond_2","dynamic_range","condition_level","requiere","bottom","top")], footer:"Fronteras y límites conceptuales; no están a escala ni son universales."},
  "U05-DG-009": {classification:"ecuación anotada", title:"Octava: razón 2:1, no diferencia fija en Hz", source:"Libro del curso, ecuaciones de bandas; valores teóricos, no tolerancias normativas.", caption:"Eje conceptual de una octava centrada en 1000 Hz y tres tercios contiguos con límites calculados.", alt:"Una barra superior va de 707,1 a 1414,2 hertz y representa una octava. Tres cajas inferiores muestran tercios contiguos con centros 793,7, 1000 y 1259,9 hertz; sus anchos absolutos aumentan.", nodes:[
    n("octave",185,145,910,105,"Octava: 707,1 Hz  →  f_c=1000 Hz  →  1414,2 Hz","f_H/f_L = 2","accent"),
    n("third_low",185,350,280,155,"1.er tercio","f_c=793,7 Hz\nB=183,8 Hz","physical"),n("third_mid",500,350,280,155,"2.º tercio","f_c=1000 Hz\nB=231,6 Hz","neutral"),n("third_high",815,350,280,155,"3.er tercio","f_c=1259,9 Hz\nB=291,8 Hz","clinical")], edges:[e("oct_1","third_low","third_mid","contiguo"),e("oct_2","third_mid","third_high","contiguo")], footer:"f_c=√(f_L f_H)      ·      f_L=f_c·2^(−1/2b)      ·      f_H=f_c·2^(1/2b)"},
  "U05-DG-010": {classification:"diagrama conceptual", title:"El tipo de filtro indica qué región pasa y cuál se atenúa", source:"Libro del curso, sección 5.9; curvas cuantitativas en U05-CH-016.", caption:"Taxonomía de cuatro filtros vinculada con una cadena entrada–filtro–salida.", alt:"Una cadena superior conecta entrada, filtro y salida. Desde el filtro parten cuatro ramas sin cruces hacia pasa bajos, pasa altos, pasa banda y elimina banda.", nodes:[
    n("filter_input",120,135,250,115,"Entrada","espectro X(f)","physical"),n("filter_system",515,135,250,115,"Filtro","respuesta H(f)","accent"),n("filter_output",910,135,250,115,"Salida","Y(f)=X(f)H(f)","physical"),
    n("lowpass",75,420,240,115,"Pasa bajos","pasa f bajas","neutral"),n("highpass",365,420,240,115,"Pasa altos","pasa f altas","neutral"),n("bandpass",655,420,240,115,"Pasa banda","pasa f_L…f_H","clinical"),n("bandstop",945,420,240,115,"Rechazo","f_L…f_H","clinical")], edges:[e("filter_1","filter_input","filter_system","pasa por"),e("filter_2","filter_system","filter_output","produce"),e("filter_branch_1","filter_system","lowpass","","bottom","top"),e("filter_branch_2","filter_system","highpass","","bottom","top"),e("filter_branch_3","filter_system","bandpass","","bottom","top"),e("filter_branch_4","filter_system","bandstop","","bottom","top")], footer:"Frecuencia de corte: declarar criterio · ideal y real no son equivalentes."},
  "U05-DG-012": {classification:"diagrama de proceso", title:"El nivel informado resulta de una cadena de decisiones", source:"Libro del curso, sección 5.11 y figura 5.8.", caption:"Cadena funcional conceptual de un sonómetro desde la presión acústica hasta el informe.", alt:"Seis bloques conectados muestran micrófono, acondicionamiento y conversión, ponderación frecuencial, detector o integrador, respuesta temporal e indicador e informe.", nodes:[
    n("meter_mic",90,155,300,130,"1 · Micrófono","p(t) en Pa","physical"),n("meter_pre",490,155,300,130,"2 · Conversión","señal digital","neutral"),n("meter_freq",890,155,300,130,"3 · Ponderación","A · C · Z","accent"),n("meter_detect",890,390,300,130,"4 · Detector","RMS o pico","neutral"),n("meter_time",490,390,300,130,"5 · Temporal","F o S","clinical"),n("meter_report",90,390,300,130,"6 · Informe","magnitud · T","clinical")], edges:[e("meter_1","meter_mic","meter_pre"),e("meter_2","meter_pre","meter_freq"),e("meter_3","meter_freq","meter_detect","","bottom","top"),e("meter_4","meter_detect","meter_time","","left","right"),e("meter_5","meter_time","meter_report","","left","right")], footer:"Cadena conceptual; no representa la arquitectura interna de un modelo comercial."},
  "U05-DG-013": {classification:"diagrama de proceso", title:"La pregunta profesional determina la representación", source:"Storyboard U05, actividad integradora.", caption:"Árbol de decisión que separa preguntas sobre señal, sistema y medición.", alt:"Una pregunta inicial se divide en tres rutas: señal, sistema y medición. Cada ruta termina en una representación y recuerda declarar evidencia y límites.", nodes:[
    n("decision_question",390,115,500,105,"¿Qué objeto necesito describir?","elegir antes de graficar","accent"),
    n("decision_signal",90,310,300,135,"Señal","tiempo · espectro","physical"),n("decision_system",490,310,300,135,"Sistema","respuesta H(f)","neutral"),n("decision_measure",890,310,300,135,"Medición","bandas · X","clinical"),
    n("decision_limit",390,500,500,130,"En toda ruta","método · unidad · límite","neutral")], edges:[e("decision_1","decision_question","decision_signal","¿cambia la señal?","bottom","top"),e("decision_2","decision_question","decision_system","¿modifica?","bottom","top"),e("decision_3","decision_question","decision_measure","¿se informa nivel?","bottom","top"),e("decision_4","decision_signal","decision_limit","evidencia","bottom","top"),e("decision_5","decision_system","decision_limit","evidencia","bottom","top"),e("decision_6","decision_measure","decision_limit","evidencia","bottom","top")]},
  "U05-DG-014": {classification:"diagrama conceptual", title:"Rutina acumulativa de lectura", source:"Storyboard U05; master de recapitulación parcial.", caption:"Master estable de cinco campos para recuperar objeto, ejes, unidades, parámetros y límite de interpretación.", alt:"Cinco campos en una grilla estable de dos filas. Parámetros aparece resaltado como dimensión nueva del bloque actual.", nodes:[
    n("recap_object",90,180,320,130,"Objeto","señal / sistema","physical"),n("recap_axes",480,180,320,130,"Ejes","t / f","neutral"),n("recap_units",870,180,320,130,"Unidades","s · Hz · Pa · dB","neutral"),n("recap_params",280,410,320,130,"Parámetros","ventana · N · fₛ","accent"),n("recap_limit",680,410,320,130,"Límite","alcance declarado","clinical")], edges:[], footer:"Master editable: el campo nuevo se distingue por color + rótulo + posición estable."},
  "U05-DG-015": {classification:"diagrama de proceso", title:"Ruta de solución del caso integrador", source:"Libro del curso, solución I1 y storyboard U05.", caption:"Cuatro pasos editables para resolver el caso: clasificar, calcular, interpretar y declarar condiciones.", alt:"Cuatro cajas horizontales numeradas organizan una solución. Primero se separa señal y sistema; luego se calculan parámetros; después se interpreta y finalmente se declaran condiciones y límites.", nodes:[
    n("solution_classify",75,235,265,165,"1 · Objeto","señal · sistema\nmedición","physical"),n("solution_compute",360,235,265,165,"2 · Cálculo","T_obs · Δf · H · G","accent"),n("solution_interpret",645,235,265,165,"3 · Lectura","armónicos\nenvolvente","neutral"),n("solution_conditions",930,235,265,165,"4 · Declarar","método\nunidad · límite","clinical")], edges:[e("solution_1","solution_classify","solution_compute"),e("solution_2","solution_compute","solution_interpret"),e("solution_3","solution_interpret","solution_conditions")], footer:"Usar sólo relaciones ya introducidas; el glosario funciona como índice de retorno."}
};

function styleColors(style){
  if(style==="physical") return {fill:C.fisico,line:C.teal,title:C.teal};
  if(style==="clinical") return {fill:C.clinico,line:C.ocre,title:C.ocre};
  if(style==="accent") return {fill:"#F3E8EE",line:C.bordo,title:C.bordo};
  if(style==="equation") return {fill:C.blanco,line:C.bordo,title:C.bordo};
  return {fill:C.marfil,line:C.gris,title:C.carbon};
}

function textLines(text){ return String(text||"").split("\n"); }
function esc(s){return String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function sidePoint(node,side){ if(side==="left")return{x:node.x,y:node.y+node.h/2}; if(side==="right")return{x:node.x+node.w,y:node.y+node.h/2}; if(side==="top")return{x:node.x+node.w/2,y:node.y}; return{x:node.x+node.w/2,y:node.y+node.h}; }
function edgePath(model,edge){ const a=model.nodes.find(x=>x.id===edge.from), b=model.nodes.find(x=>x.id===edge.to); const p=sidePoint(a,edge.fromSide), q=sidePoint(b,edge.toSide); if(edge.fromSide===edge.toSide && edge.fromSide==="bottom"){ const y=Math.max(p.y,q.y)+35; return [p,{x:p.x,y},{x:q.x,y},q]; } if((edge.fromSide==="bottom"&&edge.toSide==="top")||(edge.fromSide==="top"&&edge.toSide==="bottom")){ const y=(p.y+q.y)/2; return [p,{x:p.x,y},{x:q.x,y},q]; } if((edge.fromSide==="right"&&edge.toSide==="left")||(edge.fromSide==="left"&&edge.toSide==="right")){ const x=(p.x+q.x)/2; return [p,{x,y:p.y},{x,y:q.y},q]; } return [p,q]; }
function labelPosition(model,edge){ const pts=edgePath(model,edge); const a=pts[Math.floor((pts.length-1)/2)],b=pts[Math.ceil((pts.length-1)/2)]; return {x:(a.x+b.x)/2-58,y:(a.y+b.y)/2-46,w:116,h:28}; }

function addText(slide,name,pos,text,fontSize,color,bold=false,align="center",fill="none"){
  const s=slide.shapes.add({geometry:"textbox",name,position:{left:pos.x,top:pos.y,width:pos.w,height:pos.h},fill,line:{style:"solid",fill:"none",width:0}});
  s.text=text; s.text.style={fontSize,bold,color,alignment:align,fontFamily:"Calibri"}; return s;
}
function addNodeBackground(slide,node){ const sc=styleColors(node.style); return slide.shapes.add({geometry:"roundRect",name:`${node.id}_box`,position:{left:node.x,top:node.y,width:node.w,height:node.h},fill:sc.fill,line:{style:"solid",fill:sc.line,width:2},borderRadius:12}); }
function addNodeText(slide,node){ const sc=styleColors(node.style); const titleOnly=!node.body; const titleY=node.y+(titleOnly?24:18); const titleH=titleOnly?node.h-48:40; addText(slide,`${node.id}_title`,{x:node.x+20,y:titleY,w:node.w-40,h:titleH},node.title,node.style==="equation"?44:32,sc.title,true); if(node.body) addText(slide,`${node.id}_body`,{x:node.x+20,y:node.y+62,w:node.w-40,h:node.h-70},node.body,node.style==="equation"?30:30,C.carbon,false); }

async function writeBlob(file,blob){await fs.writeFile(file,new Uint8Array(await blob.arrayBuffer()));}

function buildSvg(model){
  const parts=[`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">`,`<defs><marker id="arrow" markerWidth="10" markerHeight="8" refX="9" refY="4" orient="auto"><path d="M0,0 L10,4 L0,8 Z" fill="${C.carbon}"/></marker></defs>`,`<rect width="1280" height="720" fill="white"/>`,`<rect x="72" y="27" width="390" height="6" fill="${C.bordo}"/><rect x="472" y="27" width="390" height="6" fill="${C.bordo2}"/><rect x="872" y="27" width="336" height="6" fill="${C.gris}"/>`,`<text x="72" y="78" font-family="Calibri,Arial,sans-serif" font-size="42" font-weight="700" fill="${C.carbon}">${esc(model.title)}</text>`];
  for(const edge of model.edges){ const pts=edgePath(model,edge); parts.push(`<polyline points="${pts.map(p=>`${p.x},${p.y}`).join(" ")}" fill="none" stroke="${C.carbon}" stroke-width="3" marker-end="url(#arrow)"/>`); if(edge.label){const lp=labelPosition(model,edge);parts.push(`<rect x="${lp.x}" y="${lp.y}" width="${lp.w}" height="${lp.h}" rx="4" fill="white"/><text x="${lp.x+lp.w/2}" y="${lp.y+21}" text-anchor="middle" font-family="Calibri,Arial,sans-serif" font-size="27" fill="${C.carbon}">${esc(edge.label)}</text>`);} }
  for(const node of model.nodes){ const sc=styleColors(node.style); parts.push(`<rect id="${node.id}" x="${node.x}" y="${node.y}" width="${node.w}" height="${node.h}" rx="12" fill="${sc.fill}" stroke="${sc.line}" stroke-width="2"/>`); const titleSize=node.style==="equation"?44:32, bodySize=30; const titleLines=textLines(node.title), bodyLines=textLines(node.body); const titleY=node.y+(node.body?42:node.h/2+titleSize/3); titleLines.forEach((line,i)=>parts.push(`<text x="${node.x+node.w/2}" y="${titleY+i*38}" text-anchor="middle" font-family="Calibri,Arial,sans-serif" font-size="${titleSize}" font-weight="700" fill="${sc.title}">${esc(line)}</text>`)); bodyLines.filter(Boolean).forEach((line,i)=>parts.push(`<text x="${node.x+node.w/2}" y="${node.y+89+i*32}" text-anchor="middle" font-family="Calibri,Arial,sans-serif" font-size="${bodySize}" fill="${C.carbon}">${esc(line)}</text>`)); }
  if(model.footer) parts.push(`<text x="640" y="625" text-anchor="middle" font-family="Calibri,Arial,sans-serif" font-size="30" fill="${C.carbon}">${esc(model.footer)}</text>`);
  parts.push(`<text x="72" y="689" font-family="Calibri,Arial,sans-serif" font-size="16" fill="${C.gris}">${esc(model.source)}</text>`,`</svg>`); return parts.join("\n");
}

function rectOverlap(a,b,pad=0){return a.x < b.x+b.w+pad && a.x+a.w+pad > b.x && a.y < b.y+b.h+pad && a.y+a.h+pad > b.y;}
function segmentIntersectsRect(a,b,r,margin=10){ const rr={x:r.x-margin,y:r.y-margin,w:r.w+2*margin,h:r.h+2*margin}; if(a.x===b.x) return a.x>=rr.x&&a.x<=rr.x+rr.w&&Math.max(Math.min(a.y,b.y),rr.y)<=Math.min(Math.max(a.y,b.y),rr.y+rr.h); if(a.y===b.y) return a.y>=rr.y&&a.y<=rr.y+rr.h&&Math.max(Math.min(a.x,b.x),rr.x)<=Math.min(Math.max(a.x,b.x),rr.x+rr.w); return false; }
function validateModel(id,model){
  const issues=[]; for(const node of model.nodes){ if(node.x<SAFE.left||node.y<SAFE.top||node.x+node.w>SAFE.right||node.y+node.h>SAFE.bottom) issues.push({severity:"major",code:"outside_safe_frame",object:node.id}); const chars=Math.floor((node.w-40)/(29*.48)); for(const line of [...textLines(node.title),...textLines(node.body)]) if(line.length>chars*1.50) issues.push({severity:"major",code:"text_fit_risk",object:node.id,line}); }
  for(let i=0;i<model.nodes.length;i++) for(let j=i+1;j<model.nodes.length;j++) if(rectOverlap(model.nodes[i],model.nodes[j],8)) issues.push({severity:"major",code:"node_overlap",objects:[model.nodes[i].id,model.nodes[j].id]});
  for(const edge of model.edges){ const pts=edgePath(model,edge); for(const node of model.nodes){ if(node.id===edge.from||node.id===edge.to) continue; for(let k=0;k<pts.length-1;k++) if(segmentIntersectsRect(pts[k],pts[k+1],node,10)) issues.push({severity:"major",code:"connector_hits_node",connector:edge.id,node:node.id}); } if(edge.label){const lp=labelPosition(model,edge); const pts2=edgePath(model,edge); for(let k=0;k<pts2.length-1;k++){ const a=pts2[k],b=pts2[k+1]; if(segmentIntersectsRect(a,b,lp,0)){ const horizontal=a.y===b.y && Math.abs((lp.y+lp.h)-a.y)>=10; const vertical=a.x===b.x && Math.abs((lp.x+lp.w)-a.x)>=10; if(!horizontal&&!vertical) issues.push({severity:"major",code:"label_on_connector",connector:edge.id}); } } } }
  return {asset_id:id,classification:model.classification,canvas_px:[W,H],slide_ratio:"16:9",font_floor:{node_title_pt:24,node_body_pt:22.5,connector_label_pt:20.25,equation_pt:33},padding_px:20,padding_inches:0.208,not_to_scale:/no est[aá] a escala|conceptual/i.test(model.footer||""),object_ids:model.nodes.map(x=>x.id),connector_ids:model.edges.map(x=>x.id),issues,critical_issues:issues.filter(x=>x.severity==="critical").length,major_issues:issues.filter(x=>x.severity==="major").length,status:issues.length?"needs_revision":"approved"};
}

async function generate(id){
  const model=MODELS[id]; const folder=path.join(ROOT,id); await fs.mkdir(folder,{recursive:true}); const validation=validateModel(id,model); if(validation.major_issues) throw new Error(`${id}: validación geométrica falló: ${JSON.stringify(validation.issues)}`);
  const pres=Presentation.create({slideSize:{width:W,height:H}}); const slide=pres.slides.add(); slide.background.fill=C.blanco;
  slide.shapes.add({geometry:"rect",name:"top_rule_bordo",position:{left:72,top:27,width:390,height:6},fill:C.bordo,line:{style:"solid",fill:"none",width:0}}); slide.shapes.add({geometry:"rect",name:"top_rule_bordo2",position:{left:472,top:27,width:390,height:6},fill:C.bordo2,line:{style:"solid",fill:"none",width:0}}); slide.shapes.add({geometry:"rect",name:"top_rule_gray",position:{left:872,top:27,width:336,height:6},fill:C.gris,line:{style:"solid",fill:"none",width:0}});
  addText(slide,"diagram_title",{x:72,y:44,w:1136,h:48},model.title,40,C.carbon,true,"left");
  const backgrounds=new Map(); for(const node of model.nodes) backgrounds.set(node.id,addNodeBackground(slide,node));
  for(const edge of model.edges){ const connector=slide.shapes.connect(backgrounds.get(edge.from),backgrounds.get(edge.to),{kind:"elbow",fromSide:edge.fromSide,toSide:edge.toSide,line:{style:"solid",fill:C.carbon,width:3},tail:{type:"arrow",width:"med",length:"med"}}); connector.name=edge.id; if(edge.label){const lp=labelPosition(model,edge); addText(slide,`${edge.id}_label`,lp,edge.label,27,C.carbon,false,"center",C.blanco);} }
  for(const node of model.nodes) addNodeText(slide,node); if(model.footer) addText(slide,"diagram_footer",{x:82,y:592,w:1116,h:42},model.footer,30,C.carbon,false);
  addText(slide,"source_note",{x:72,y:670,w:1136,h:24},model.source,16,C.gris,false,"left");
  const base=`u05_dg_${id.slice(-3)}_master`; await writeBlob(path.join(folder,`${base}.png`),await pres.export({slide,format:"png",scale:2})); await fs.writeFile(path.join(folder,`${base}.layout.json`),await (await slide.export({format:"layout"})).text()); const pptx=await PresentationFile.exportPptx(pres); await pptx.save(path.join(folder,`${base}.pptx`)); await fs.writeFile(path.join(folder,`${base}.svg`),buildSvg(model),"utf8"); await fs.writeFile(path.join(folder,"diagram_source.json"),JSON.stringify(model,null,2),"utf8");
  const readme=`# ${id}\n\n- **Clasificación:** ${model.classification}\n- **Estado:** aprobado tras validación geométrica y render 16:9.\n- **Fuente conceptual:** ${model.source}\n- **Editabilidad:** ${base}.pptx conserva textos, cajas y conectores; diagram_source.json conserva geometría, IDs y semántica de cada relación.\n- **Reproducción:** ejecutar units/unit_05/scripts/u05_generate_diagrams.mjs con U05_ARTIFACT_WORKSPACE configurado.\n\n## Caption sugerido\n\n${model.caption}\n\n## Texto alternativo\n\n${model.alt}\n\n## Validación\n\n- texto principal: 22,5 pt efectivo; títulos de nodo: 24 pt; ecuaciones: 33 pt;\n- padding: 20 px = 0,208 in;\n- conectores anclados y enviados detrás de los nodos; la semántica se trasladó a los nodos para evitar etiquetas sobre líneas;\n- preview renderizado a 2560×1440;\n- figura conceptual no a escala: ${validation.not_to_scale?"sí":"no / no corresponde"};\n- problemas críticos: 0; problemas mayores: 0.\n`;
  await fs.writeFile(path.join(folder,"README.md"),readme,"utf8"); await fs.writeFile(path.join(folder,"validation.json"),JSON.stringify(validation,null,2),"utf8"); return validation;
}

const arg=process.argv[2]; const ids=arg?[arg]:Object.keys(MODELS); if(arg&&!MODELS[arg]) throw new Error(`ID no aprobado: ${arg}`);
const preflight=ids.map(id=>validateModel(id,MODELS[id])); const failed=preflight.filter(v=>v.major_issues||v.critical_issues); if(failed.length) throw new Error(`Preflight geométrico: ${JSON.stringify(failed.map(v=>({asset_id:v.asset_id,issues:v.issues})))}`);
const results=[]; for(const id of ids) results.push(await generate(id)); await fs.mkdir(ROOT,{recursive:true}); await fs.writeFile(path.join(ROOT,"generation_summary.json"),JSON.stringify(results,null,2),"utf8"); console.log(`Generadas ${results.length} familias en ${ROOT}`);
